// Auto-generated by scripts/listImageKit.ts — do not edit by hand.
// Re-run `pnpm imagekit:list` after uploading new assets to ImageKit.

export type ImageKitCatalogEntry = {
  fileId: string
  name: string
  folder: string
  filePath: string
  url: string
  width?: number
  height?: number
  alt: string
}

export const IMAGEKIT_ROOT = "/punyakoti-taila" as const

export const IMAGEKIT_FOLDERS: ReadonlyArray<{ folderPath: string; name: string }> = [
  {
    "folderPath": "/punyakoti-taila/brand",
    "name": "brand"
  },
  {
    "folderPath": "/punyakoti-taila/collections",
    "name": "collections"
  },
  {
    "folderPath": "/punyakoti-taila/food",
    "name": "food"
  },
  {
    "folderPath": "/punyakoti-taila/gifting",
    "name": "gifting"
  },
  {
    "folderPath": "/punyakoti-taila/home",
    "name": "home"
  },
  {
    "folderPath": "/punyakoti-taila/ingredients",
    "name": "ingredients"
  },
  {
    "folderPath": "/punyakoti-taila/others",
    "name": "others"
  },
  {
    "folderPath": "/punyakoti-taila/people",
    "name": "people"
  },
  {
    "folderPath": "/punyakoti-taila/process",
    "name": "process"
  },
  {
    "folderPath": "/punyakoti-taila/products",
    "name": "products"
  },
  {
    "folderPath": "/punyakoti-taila/products/achaar-pickles",
    "name": "achaar-pickles"
  },
  {
    "folderPath": "/punyakoti-taila/products/all-oils",
    "name": "all-oils"
  },
  {
    "folderPath": "/punyakoti-taila/products/almond-oil",
    "name": "almond-oil"
  },
  {
    "folderPath": "/punyakoti-taila/products/castor-oil",
    "name": "castor-oil"
  },
  {
    "folderPath": "/punyakoti-taila/products/coconut-oil",
    "name": "coconut-oil"
  },
  {
    "folderPath": "/punyakoti-taila/products/dant-manjan",
    "name": "dant-manjan"
  },
  {
    "folderPath": "/punyakoti-taila/products/dhoop-batti",
    "name": "dhoop-batti"
  },
  {
    "folderPath": "/punyakoti-taila/products/gomutra-ark",
    "name": "gomutra-ark"
  },
  {
    "folderPath": "/punyakoti-taila/products/groundnut-oil",
    "name": "groundnut-oil"
  },
  {
    "folderPath": "/punyakoti-taila/products/real-photos",
    "name": "real-photos"
  },
  {
    "folderPath": "/punyakoti-taila/products/safflower-oil",
    "name": "safflower-oil"
  },
  {
    "folderPath": "/punyakoti-taila/products/sesame-oil",
    "name": "sesame-oil"
  },
  {
    "folderPath": "/punyakoti-taila/store",
    "name": "store"
  },
  {
    "folderPath": "/punyakoti-taila/ui-mockups",
    "name": "ui-mockups"
  },
  {
    "folderPath": "/punyakoti-taila/ui-mockups/claude",
    "name": "claude"
  },
  {
    "folderPath": "/punyakoti-taila/ui-mockups/stitch",
    "name": "stitch"
  },
  {
    "folderPath": "/punyakoti-taila/wellness",
    "name": "wellness"
  }
] as const

export const IMAGEKIT_CATALOG: ReadonlyArray<ImageKitCatalogEntry> = [
  {
    "fileId": "6a2ae1665c7cd75eb8b3554f",
    "name": "diya-rangoli-heritage-culture.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/diya-rangoli-heritage-culture.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/diya-rangoli-heritage-culture.png",
    "width": 1024,
    "height": 1024,
    "alt": "brand/diya-rangoli-heritage-culture"
  },
  {
    "fileId": "6a2ae16a5c7cd75eb8b37229",
    "name": "elderly-hands-holding-seeds-heritage.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/elderly-hands-holding-seeds-heritage.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/elderly-hands-holding-seeds-heritage.png",
    "width": 1264,
    "height": 848,
    "alt": "brand/elderly-hands-holding-seeds-heritage"
  },
  {
    "fileId": "6a153c985c7cd75eb82d0eb7",
    "name": "logo_only_with_bg.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/logo_only_with_bg.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/logo_only_with_bg.png",
    "width": 1402,
    "height": 768,
    "alt": "brand/logo_only_with_bg"
  },
  {
    "fileId": "6a142c1e5c7cd75eb8920630",
    "name": "logo-brand-sheet.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/logo-brand-sheet.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/logo-brand-sheet.png",
    "width": 1600,
    "height": 878,
    "alt": "brand/logo-brand-sheet"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317ae",
    "name": "logo-on-wood-press.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/logo-on-wood-press.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/logo-on-wood-press.png",
    "width": 1024,
    "height": 1024,
    "alt": "brand/logo-on-wood-press"
  },
  {
    "fileId": "6a1539f95c7cd75eb8188bcc",
    "name": "logo-opttions.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/logo-opttions.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/logo-opttions.png",
    "width": 1402,
    "height": 768,
    "alt": "brand/logo-opttions"
  },
  {
    "fileId": "6a1539fb5c7cd75eb8189b97",
    "name": "logo-with-bg.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/logo-with-bg.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/logo-with-bg.png",
    "width": 1402,
    "height": 768,
    "alt": "brand/logo-with-bg"
  },
  {
    "fileId": "6a153c9a5c7cd75eb82d250b",
    "name": "only_logo_image_no_bg.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/only_logo_image_no_bg.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/only_logo_image_no_bg.png",
    "width": 1402,
    "height": 768,
    "alt": "brand/only_logo_image_no_bg"
  },
  {
    "fileId": "6a1427e75c7cd75eb8789efa",
    "name": "punyakoti_logo.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/punyakoti_logo.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/punyakoti_logo.png",
    "width": 1693,
    "height": 929,
    "alt": "brand/punyakoti_logo"
  },
  {
    "fileId": "6a2ae1735c7cd75eb8b3a8d7",
    "name": "punyakoti-brand-banner-sesame-groundnut.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/punyakoti-brand-banner-sesame-groundnut.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/punyakoti-brand-banner-sesame-groundnut.png",
    "width": 1402,
    "height": 768,
    "alt": "brand/punyakoti-brand-banner-sesame-groundnut"
  },
  {
    "fileId": "6a1539fd5c7cd75eb818a9b7",
    "name": "punyakoti-logo-no-bg.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/punyakoti-logo-no-bg.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/punyakoti-logo-no-bg.png",
    "width": 2804,
    "height": 1536,
    "alt": "brand/punyakoti-logo-no-bg"
  },
  {
    "fileId": "6a2ae1765c7cd75eb8b3cb5b",
    "name": "punyakoti-taila-logo-transparent.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/punyakoti-taila-logo-transparent.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/punyakoti-taila-logo-transparent.png",
    "width": 1402,
    "height": 768,
    "alt": "brand/punyakoti-taila-logo-transparent"
  },
  {
    "fileId": "6a2ae1785c7cd75eb8b3d648",
    "name": "punyakoti-taila-logo-white-bg.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/punyakoti-taila-logo-white-bg.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/punyakoti-taila-logo-white-bg.png",
    "width": 2804,
    "height": 1536,
    "alt": "brand/punyakoti-taila-logo-white-bg"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317bc",
    "name": "all-five-oils.png",
    "folder": "/punyakoti-taila/collections",
    "filePath": "/punyakoti-taila/collections/all-five-oils.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/collections/all-five-oils.png",
    "width": 1024,
    "height": 1024,
    "alt": "collections/all-five-oils"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317bf",
    "name": "dropper-trio-coconut-almond-sesame.png",
    "folder": "/punyakoti-taila/collections",
    "filePath": "/punyakoti-taila/collections/dropper-trio-coconut-almond-sesame.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/collections/dropper-trio-coconut-almond-sesame.png",
    "width": 1200,
    "height": 896,
    "alt": "collections/dropper-trio-coconut-almond-sesame"
  },
  {
    "fileId": "6a140f075c7cd75eb8c326cf",
    "name": "full-range-all-products.png",
    "folder": "/punyakoti-taila/collections",
    "filePath": "/punyakoti-taila/collections/full-range-all-products.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/collections/full-range-all-products.png",
    "width": 1693,
    "height": 929,
    "alt": "collections/full-range-all-products"
  },
  {
    "fileId": "6a140f075c7cd75eb8c326fe",
    "name": "full-range-large-bottles.png",
    "folder": "/punyakoti-taila/collections",
    "filePath": "/punyakoti-taila/collections/full-range-large-bottles.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/collections/full-range-large-bottles.png",
    "width": 1693,
    "height": 929,
    "alt": "collections/full-range-large-bottles"
  },
  {
    "fileId": "6a142ceb5c7cd75eb897439a",
    "name": "hero_image_half_multi.png",
    "folder": "/punyakoti-taila/collections",
    "filePath": "/punyakoti-taila/collections/hero_image_half_multi.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/collections/hero_image_half_multi.png",
    "width": 1536,
    "height": 1024,
    "alt": "collections/hero_image_half_multi"
  },
  {
    "fileId": "6a2ae17f5c7cd75eb8b4029e",
    "name": "three-amber-bottles-mustard-safflower-groundnut.png",
    "folder": "/punyakoti-taila/collections",
    "filePath": "/punyakoti-taila/collections/three-amber-bottles-mustard-safflower-groundnut.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/collections/three-amber-bottles-mustard-safflower-groundnut.png",
    "width": 1264,
    "height": 848,
    "alt": "collections/three-amber-bottles-mustard-safflower-groundnut"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317c8",
    "name": "three-bottles-row.png",
    "folder": "/punyakoti-taila/collections",
    "filePath": "/punyakoti-taila/collections/three-bottles-row.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/collections/three-bottles-row.png",
    "width": 1024,
    "height": 1024,
    "alt": "collections/three-bottles-row"
  },
  {
    "fileId": "6a2ae1815c7cd75eb8b41518",
    "name": "artisan-bread-oil-dipping-bowl.png",
    "folder": "/punyakoti-taila/food",
    "filePath": "/punyakoti-taila/food/artisan-bread-oil-dipping-bowl.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/food/artisan-bread-oil-dipping-bowl.png",
    "width": 1024,
    "height": 1024,
    "alt": "food/artisan-bread-oil-dipping-bowl"
  },
  {
    "fileId": "6a2ae1855c7cd75eb8b4492a",
    "name": "brass-kadai-oil-pour-sizzling.png",
    "folder": "/punyakoti-taila/food",
    "filePath": "/punyakoti-taila/food/brass-kadai-oil-pour-sizzling.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/food/brass-kadai-oil-pour-sizzling.png",
    "width": 1024,
    "height": 1024,
    "alt": "food/brass-kadai-oil-pour-sizzling"
  },
  {
    "fileId": "6a2ae1895c7cd75eb8b478a3",
    "name": "mango-pickle-oil-pour-spices.png",
    "folder": "/punyakoti-taila/food",
    "filePath": "/punyakoti-taila/food/mango-pickle-oil-pour-spices.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/food/mango-pickle-oil-pour-spices.png",
    "width": 1264,
    "height": 848,
    "alt": "food/mango-pickle-oil-pour-spices"
  },
  {
    "fileId": "6a2ae18b5c7cd75eb8b48bec",
    "name": "modern-kitchen-vegetables-punyakoti-bottle.png",
    "folder": "/punyakoti-taila/food",
    "filePath": "/punyakoti-taila/food/modern-kitchen-vegetables-punyakoti-bottle.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/food/modern-kitchen-vegetables-punyakoti-bottle.png",
    "width": 1264,
    "height": 848,
    "alt": "food/modern-kitchen-vegetables-punyakoti-bottle"
  },
  {
    "fileId": "6a2ae18c5c7cd75eb8b499e4",
    "name": "rice-plate-curry-punyakoti-bottle.png",
    "folder": "/punyakoti-taila/food",
    "filePath": "/punyakoti-taila/food/rice-plate-curry-punyakoti-bottle.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/food/rice-plate-curry-punyakoti-bottle.png",
    "width": 1024,
    "height": 1024,
    "alt": "food/rice-plate-curry-punyakoti-bottle"
  },
  {
    "fileId": "6a2ae18e5c7cd75eb8b4a750",
    "name": "traditional-breakfast-idli-punyakoti-bottle.png",
    "folder": "/punyakoti-taila/food",
    "filePath": "/punyakoti-taila/food/traditional-breakfast-idli-punyakoti-bottle.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/food/traditional-breakfast-idli-punyakoti-bottle.png",
    "width": 1264,
    "height": 848,
    "alt": "food/traditional-breakfast-idli-punyakoti-bottle"
  },
  {
    "fileId": "6a2ae1905c7cd75eb8b4b6fd",
    "name": "traditional-kitchen-mortar-herbs-bottle.png",
    "folder": "/punyakoti-taila/food",
    "filePath": "/punyakoti-taila/food/traditional-kitchen-mortar-herbs-bottle.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/food/traditional-kitchen-mortar-herbs-bottle.png",
    "width": 1264,
    "height": 848,
    "alt": "food/traditional-kitchen-mortar-herbs-bottle"
  },
  {
    "fileId": "6a2ae1925c7cd75eb8b4c788",
    "name": "eco-kraft-box-wrapping-dried-herbs.png",
    "folder": "/punyakoti-taila/gifting",
    "filePath": "/punyakoti-taila/gifting/eco-kraft-box-wrapping-dried-herbs.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/gifting/eco-kraft-box-wrapping-dried-herbs.png",
    "width": 1264,
    "height": 848,
    "alt": "gifting/eco-kraft-box-wrapping-dried-herbs"
  },
  {
    "fileId": "6a140f025c7cd75eb8c31414",
    "name": "hero-unboxing.png",
    "folder": "/punyakoti-taila/gifting",
    "filePath": "/punyakoti-taila/gifting/hero-unboxing.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/gifting/hero-unboxing.png",
    "width": 1200,
    "height": 896,
    "alt": "gifting/hero-unboxing"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317ce",
    "name": "kraft-boxes-branded.png",
    "folder": "/punyakoti-taila/gifting",
    "filePath": "/punyakoti-taila/gifting/kraft-boxes-branded.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/gifting/kraft-boxes-branded.png",
    "width": 1200,
    "height": 896,
    "alt": "gifting/kraft-boxes-branded"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317b6",
    "name": "kraft-boxes-generic.png",
    "folder": "/punyakoti-taila/gifting",
    "filePath": "/punyakoti-taila/gifting/kraft-boxes-generic.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/gifting/kraft-boxes-generic.png",
    "width": 1024,
    "height": 1024,
    "alt": "gifting/kraft-boxes-generic"
  },
  {
    "fileId": "6a140f035c7cd75eb8c3189d",
    "name": "safflower-gift-box.png",
    "folder": "/punyakoti-taila/gifting",
    "filePath": "/punyakoti-taila/gifting/safflower-gift-box.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/gifting/safflower-gift-box.png",
    "width": 1024,
    "height": 1024,
    "alt": "gifting/safflower-gift-box"
  },
  {
    "fileId": "6a140f065c7cd75eb8c324d4",
    "name": "banner-ingredients-table.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/banner-ingredients-table.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/banner-ingredients-table.png",
    "width": 1024,
    "height": 1024,
    "alt": "home/banner-ingredients-table"
  },
  {
    "fileId": "6a140f035c7cd75eb8c319ce",
    "name": "banner-multi-panel.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/banner-multi-panel.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/banner-multi-panel.png",
    "width": 1536,
    "height": 1024,
    "alt": "home/banner-multi-panel"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32577",
    "name": "hero-01-ayurveda-bowl.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/hero-01-ayurveda-bowl.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/hero-01-ayurveda-bowl.png",
    "width": 1376,
    "height": 768,
    "alt": "home/hero-01-ayurveda-bowl"
  },
  {
    "fileId": "6a140f065c7cd75eb8c322ca",
    "name": "hero-02-product-range.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/hero-02-product-range.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/hero-02-product-range.png",
    "width": 1376,
    "height": 768,
    "alt": "home/hero-02-product-range"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317e9",
    "name": "hero-03-dropper-trio.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/hero-03-dropper-trio.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/hero-03-dropper-trio.png",
    "width": 1376,
    "height": 768,
    "alt": "home/hero-03-dropper-trio"
  },
  {
    "fileId": "6a140f065c7cd75eb8c325ca",
    "name": "hero-04-bottles-ingredients.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/hero-04-bottles-ingredients.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/hero-04-bottles-ingredients.png",
    "width": 1376,
    "height": 768,
    "alt": "home/hero-04-bottles-ingredients"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32611",
    "name": "hero-05-warm-golden-bottle.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/hero-05-warm-golden-bottle.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/hero-05-warm-golden-bottle.png",
    "width": 1717,
    "height": 916,
    "alt": "home/hero-05-warm-golden-bottle"
  },
  {
    "fileId": "6a140f035c7cd75eb8c319e3",
    "name": "hero-06-branded-box-bottle.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/hero-06-branded-box-bottle.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/hero-06-branded-box-bottle.png",
    "width": 1536,
    "height": 1024,
    "alt": "home/hero-06-branded-box-bottle"
  },
  {
    "fileId": "6a2ae1975c7cd75eb8b4f4ad",
    "name": "hero-safflower-bottle-raw-ingredients-sunset.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/hero-safflower-bottle-raw-ingredients-sunset.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/hero-safflower-bottle-raw-ingredients-sunset.png",
    "width": 1264,
    "height": 848,
    "alt": "home/hero-safflower-bottle-raw-ingredients-sunset"
  },
  {
    "fileId": "6a2ae1995c7cd75eb8b502b8",
    "name": "hero-three-oils-groundnut-coconut-sesame-sunset.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/hero-three-oils-groundnut-coconut-sesame-sunset.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/hero-three-oils-groundnut-coconut-sesame-sunset.png",
    "width": 1376,
    "height": 768,
    "alt": "home/hero-three-oils-groundnut-coconut-sesame-sunset"
  },
  {
    "fileId": "6a2ae19b5c7cd75eb8b50e3e",
    "name": "coconuts-sesame-clay-pots-rustic.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/coconuts-sesame-clay-pots-rustic.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/coconuts-sesame-clay-pots-rustic.png",
    "width": 1024,
    "height": 1024,
    "alt": "ingredients/coconuts-sesame-clay-pots-rustic"
  },
  {
    "fileId": "6a2ae19d5c7cd75eb8b51bae",
    "name": "golden-oil-drop-splash-brass-bowl.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/golden-oil-drop-splash-brass-bowl.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/golden-oil-drop-splash-brass-bowl.png",
    "width": 1264,
    "height": 848,
    "alt": "ingredients/golden-oil-drop-splash-brass-bowl"
  },
  {
    "fileId": "6a2ae19e5c7cd75eb8b5260b",
    "name": "golden-oil-ripples-brass-bowl.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/golden-oil-ripples-brass-bowl.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/golden-oil-ripples-brass-bowl.png",
    "width": 1264,
    "height": 848,
    "alt": "ingredients/golden-oil-ripples-brass-bowl"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32510",
    "name": "mortar-pestle-filling.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/mortar-pestle-filling.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/mortar-pestle-filling.png",
    "width": 1376,
    "height": 768,
    "alt": "ingredients/mortar-pestle-filling"
  },
  {
    "fileId": "6a140f015c7cd75eb8c312cd",
    "name": "oil-ripples-wooden-bowl.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/oil-ripples-wooden-bowl.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/oil-ripples-wooden-bowl.png",
    "width": 1024,
    "height": 1024,
    "alt": "ingredients/oil-ripples-wooden-bowl"
  },
  {
    "fileId": "6a140f025c7cd75eb8c31774",
    "name": "raw-seeds-peanuts-coconut.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/raw-seeds-peanuts-coconut.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/raw-seeds-peanuts-coconut.png",
    "width": 1024,
    "height": 1024,
    "alt": "ingredients/raw-seeds-peanuts-coconut"
  },
  {
    "fileId": "6a2ae1a25c7cd75eb8b538df",
    "name": "sesame-oil-pour-brass-vessel-clay-bowl.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/sesame-oil-pour-brass-vessel-clay-bowl.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/sesame-oil-pour-brass-vessel-clay-bowl.png",
    "width": 1024,
    "height": 1024,
    "alt": "ingredients/sesame-oil-pour-brass-vessel-clay-bowl"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3249c",
    "name": "spoon-oil-logo-closeup.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/spoon-oil-logo-closeup.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/spoon-oil-logo-closeup.png",
    "width": 1200,
    "height": 896,
    "alt": "ingredients/spoon-oil-logo-closeup"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317cd",
    "name": "spoon-oil-over-peanuts.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/spoon-oil-over-peanuts.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/spoon-oil-over-peanuts.png",
    "width": 1024,
    "height": 1024,
    "alt": "ingredients/spoon-oil-over-peanuts"
  },
  {
    "fileId": "6a2ae1a65c7cd75eb8b54bf8",
    "name": "sun-dried-mustard-seeds-basket.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/sun-dried-mustard-seeds-basket.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/sun-dried-mustard-seeds-basket.png",
    "width": 1264,
    "height": 848,
    "alt": "ingredients/sun-dried-mustard-seeds-basket"
  },
  {
    "fileId": "6a143dcf5c7cd75eb816f26e",
    "name": "Lap-Twilights-1200x630.png",
    "folder": "/punyakoti-taila/others",
    "filePath": "/punyakoti-taila/others/Lap-Twilights-1200x630.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/others/Lap-Twilights-1200x630.png",
    "width": 1200,
    "height": 630,
    "alt": "others/Lap-Twilights-1200x630"
  },
  {
    "fileId": "6a143dcf5c7cd75eb816f1ed",
    "name": "Lap-Twilights-300x350.png",
    "folder": "/punyakoti-taila/others",
    "filePath": "/punyakoti-taila/others/Lap-Twilights-300x350.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/others/Lap-Twilights-300x350.png",
    "width": 300,
    "height": 350,
    "alt": "others/Lap-Twilights-300x350"
  },
  {
    "fileId": "6a143dcf5c7cd75eb816f353",
    "name": "Lap-Twilights-500x500.png",
    "folder": "/punyakoti-taila/others",
    "filePath": "/punyakoti-taila/others/Lap-Twilights-500x500.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/others/Lap-Twilights-500x500.png",
    "width": 500,
    "height": 500,
    "alt": "others/Lap-Twilights-500x500"
  },
  {
    "fileId": "6a143dcf5c7cd75eb816f369",
    "name": "Lap-Twilights-600x700.png",
    "folder": "/punyakoti-taila/others",
    "filePath": "/punyakoti-taila/others/Lap-Twilights-600x700.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/others/Lap-Twilights-600x700.png",
    "width": 600,
    "height": 700,
    "alt": "others/Lap-Twilights-600x700"
  },
  {
    "fileId": "6a143dcf5c7cd75eb816f3b8",
    "name": "Lap-Twilights-900x1050.png",
    "folder": "/punyakoti-taila/others",
    "filePath": "/punyakoti-taila/others/Lap-Twilights-900x1050.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/others/Lap-Twilights-900x1050.png",
    "width": 900,
    "height": 1050,
    "alt": "others/Lap-Twilights-900x1050"
  },
  {
    "fileId": "6a143dcf5c7cd75eb816f334",
    "name": "Lap-Twilights.png",
    "folder": "/punyakoti-taila/others",
    "filePath": "/punyakoti-taila/others/Lap-Twilights.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/others/Lap-Twilights.png",
    "width": 1342,
    "height": 1566,
    "alt": "others/Lap-Twilights"
  },
  {
    "fileId": "6a2ae1a85c7cd75eb8b55b6b",
    "name": "portrait-chef-holding-punyakoti-bottle.png",
    "folder": "/punyakoti-taila/people",
    "filePath": "/punyakoti-taila/people/portrait-chef-holding-punyakoti-bottle.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/people/portrait-chef-holding-punyakoti-bottle.png",
    "width": 1024,
    "height": 1024,
    "alt": "people/portrait-chef-holding-punyakoti-bottle"
  },
  {
    "fileId": "6a2ae1aa5c7cd75eb8b566ef",
    "name": "portrait-elderly-man-dignified.png",
    "folder": "/punyakoti-taila/people",
    "filePath": "/punyakoti-taila/people/portrait-elderly-man-dignified.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/people/portrait-elderly-man-dignified.png",
    "width": 1024,
    "height": 1024,
    "alt": "people/portrait-elderly-man-dignified"
  },
  {
    "fileId": "6a2ae1ab5c7cd75eb8b56eac",
    "name": "portrait-middle-aged-man-vegetable-basket.png",
    "folder": "/punyakoti-taila/people",
    "filePath": "/punyakoti-taila/people/portrait-middle-aged-man-vegetable-basket.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/people/portrait-middle-aged-man-vegetable-basket.png",
    "width": 1024,
    "height": 1024,
    "alt": "people/portrait-middle-aged-man-vegetable-basket"
  },
  {
    "fileId": "6a2ae1ad5c7cd75eb8b5764b",
    "name": "portrait-middle-aged-woman-sophisticated.png",
    "folder": "/punyakoti-taila/people",
    "filePath": "/punyakoti-taila/people/portrait-middle-aged-woman-sophisticated.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/people/portrait-middle-aged-woman-sophisticated.png",
    "width": 1024,
    "height": 1024,
    "alt": "people/portrait-middle-aged-woman-sophisticated"
  },
  {
    "fileId": "6a2ae1af5c7cd75eb8b57ebe",
    "name": "portrait-young-mother-gentle-smile.png",
    "folder": "/punyakoti-taila/people",
    "filePath": "/punyakoti-taila/people/portrait-young-mother-gentle-smile.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/people/portrait-young-mother-gentle-smile.png",
    "width": 1024,
    "height": 1024,
    "alt": "people/portrait-young-mother-gentle-smile"
  },
  {
    "fileId": "6a2ae1b15c7cd75eb8b58631",
    "name": "portrait-young-professional-man.png",
    "folder": "/punyakoti-taila/people",
    "filePath": "/punyakoti-taila/people/portrait-young-professional-man.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/people/portrait-young-professional-man.png",
    "width": 1024,
    "height": 1024,
    "alt": "people/portrait-young-professional-man"
  },
  {
    "fileId": "6a2ae1b25c7cd75eb8b58f57",
    "name": "portrait-young-woman-glowing-skin.png",
    "folder": "/punyakoti-taila/people",
    "filePath": "/punyakoti-taila/people/portrait-young-woman-glowing-skin.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/people/portrait-young-woman-glowing-skin.png",
    "width": 1024,
    "height": 1024,
    "alt": "people/portrait-young-woman-glowing-skin"
  },
  {
    "fileId": "6a2ae1b45c7cd75eb8b598c1",
    "name": "coconut-drying-yard-heritage-est-1920.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/coconut-drying-yard-heritage-est-1920.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/coconut-drying-yard-heritage-est-1920.png",
    "width": 1264,
    "height": 848,
    "alt": "process/coconut-drying-yard-heritage-est-1920"
  },
  {
    "fileId": "6a140f065c7cd75eb8c325a9",
    "name": "ghana-press-oil-flowing.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/ghana-press-oil-flowing.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/ghana-press-oil-flowing.png",
    "width": 1024,
    "height": 1024,
    "alt": "process/ghana-press-oil-flowing"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32566",
    "name": "ghana-press-rustic.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/ghana-press-rustic.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/ghana-press-rustic.png",
    "width": 1024,
    "height": 1024,
    "alt": "process/ghana-press-rustic"
  },
  {
    "fileId": "6a140f025c7cd75eb8c315ac",
    "name": "ghana-press-studio.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/ghana-press-studio.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/ghana-press-studio.png",
    "width": 1200,
    "height": 896,
    "alt": "process/ghana-press-studio"
  },
  {
    "fileId": "6a2ae1ba5c7cd75eb8b5bbc2",
    "name": "stone-chakki-mill-oil-flowing-golden.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/stone-chakki-mill-oil-flowing-golden.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/stone-chakki-mill-oil-flowing-golden.png",
    "width": 1024,
    "height": 1024,
    "alt": "process/stone-chakki-mill-oil-flowing-golden"
  },
  {
    "fileId": "6a2ae1bc5c7cd75eb8b5c3ed",
    "name": "stone-mortar-herbs-nuts-punyakoti-bottle.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/stone-mortar-herbs-nuts-punyakoti-bottle.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/stone-mortar-herbs-nuts-punyakoti-bottle.png",
    "width": 1264,
    "height": 848,
    "alt": "process/stone-mortar-herbs-nuts-punyakoti-bottle"
  },
  {
    "fileId": "6a2ae1be5c7cd75eb8b5cce1",
    "name": "traditional-farmer-wooden-oil-press.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/traditional-farmer-wooden-oil-press.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/traditional-farmer-wooden-oil-press.png",
    "width": 1024,
    "height": 1024,
    "alt": "process/traditional-farmer-wooden-oil-press"
  },
  {
    "fileId": "6a140f035c7cd75eb8c31877",
    "name": "traditional-ghani-village.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/traditional-ghani-village.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/traditional-ghani-village.png",
    "width": 1024,
    "height": 1024,
    "alt": "process/traditional-ghani-village"
  },
  {
    "fileId": "6a2ae1c05c7cd75eb8b5d500",
    "name": "traditional-press-oil-flowing-steel-vessel.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/traditional-press-oil-flowing-steel-vessel.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/traditional-press-oil-flowing-steel-vessel.png",
    "width": 1264,
    "height": 848,
    "alt": "process/traditional-press-oil-flowing-steel-vessel"
  },
  {
    "fileId": "6a140f035c7cd75eb8c31bbc",
    "name": "wood-press-machine-branded.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/wood-press-machine-branded.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/wood-press-machine-branded.png",
    "width": 1706,
    "height": 922,
    "alt": "process/wood-press-machine-branded"
  },
  {
    "fileId": "6a140f035c7cd75eb8c319b8",
    "name": "wood-press-machine-moody.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/wood-press-machine-moody.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/wood-press-machine-moody.png",
    "width": 1672,
    "height": 941,
    "alt": "process/wood-press-machine-moody"
  },
  {
    "fileId": "6a140f065c7cd75eb8c323da",
    "name": "hero-branded-jars.png",
    "folder": "/punyakoti-taila/products/achaar-pickles",
    "filePath": "/punyakoti-taila/products/achaar-pickles/hero-branded-jars.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/achaar-pickles/hero-branded-jars.png",
    "width": 1200,
    "height": 896,
    "alt": "achaar-pickles/hero-branded-jars"
  },
  {
    "fileId": "6a2ae1c35c7cd75eb8b5e3fb",
    "name": "mustard-oil-pour-into-achaar-jar.png",
    "folder": "/punyakoti-taila/products/achaar-pickles",
    "filePath": "/punyakoti-taila/products/achaar-pickles/mustard-oil-pour-into-achaar-jar.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/achaar-pickles/mustard-oil-pour-into-achaar-jar.png",
    "width": 1024,
    "height": 1024,
    "alt": "achaar-pickles/mustard-oil-pour-into-achaar-jar"
  },
  {
    "fileId": "6a140f065c7cd75eb8c323a3",
    "name": "rustic-yellow-cap-jars.png",
    "folder": "/punyakoti-taila/products/achaar-pickles",
    "filePath": "/punyakoti-taila/products/achaar-pickles/rustic-yellow-cap-jars.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/achaar-pickles/rustic-yellow-cap-jars.png",
    "width": 1024,
    "height": 1024,
    "alt": "achaar-pickles/rustic-yellow-cap-jars"
  },
  {
    "fileId": "6a153a015c7cd75eb818bf92",
    "name": "coconut-oil.png",
    "folder": "/punyakoti-taila/products/all-oils",
    "filePath": "/punyakoti-taila/products/all-oils/coconut-oil.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/all-oils/coconut-oil.png",
    "width": 1024,
    "height": 1024,
    "alt": "all-oils/coconut-oil"
  },
  {
    "fileId": "6a153a035c7cd75eb818d816",
    "name": "groundnut-oil.png",
    "folder": "/punyakoti-taila/products/all-oils",
    "filePath": "/punyakoti-taila/products/all-oils/groundnut-oil.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/all-oils/groundnut-oil.png",
    "width": 1024,
    "height": 1024,
    "alt": "all-oils/groundnut-oil"
  },
  {
    "fileId": "6a153a055c7cd75eb818e91d",
    "name": "mustard-oil.png",
    "folder": "/punyakoti-taila/products/all-oils",
    "filePath": "/punyakoti-taila/products/all-oils/mustard-oil.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/all-oils/mustard-oil.png",
    "width": 1024,
    "height": 1024,
    "alt": "all-oils/mustard-oil"
  },
  {
    "fileId": "6a153a075c7cd75eb818f203",
    "name": "seffalower-oil.png",
    "folder": "/punyakoti-taila/products/all-oils",
    "filePath": "/punyakoti-taila/products/all-oils/seffalower-oil.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/all-oils/seffalower-oil.png",
    "width": 1024,
    "height": 1024,
    "alt": "all-oils/seffalower-oil"
  },
  {
    "fileId": "6a153a095c7cd75eb818ff74",
    "name": "sesame-oil.png",
    "folder": "/punyakoti-taila/products/all-oils",
    "filePath": "/punyakoti-taila/products/all-oils/sesame-oil.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/all-oils/sesame-oil.png",
    "width": 1024,
    "height": 1024,
    "alt": "all-oils/sesame-oil"
  },
  {
    "fileId": "6a153a0a5c7cd75eb8190b53",
    "name": "sunflower-oil.png",
    "folder": "/punyakoti-taila/products/all-oils",
    "filePath": "/punyakoti-taila/products/all-oils/sunflower-oil.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/all-oils/sunflower-oil.png",
    "width": 1024,
    "height": 1024,
    "alt": "all-oils/sunflower-oil"
  },
  {
    "fileId": "6a140f025c7cd75eb8c3145d",
    "name": "hero-dropper.png",
    "folder": "/punyakoti-taila/products/almond-oil",
    "filePath": "/punyakoti-taila/products/almond-oil/hero-dropper.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/almond-oil/hero-dropper.png",
    "width": 1024,
    "height": 1024,
    "alt": "almond-oil/hero-dropper"
  },
  {
    "fileId": "6a140f055c7cd75eb8c321d6",
    "name": "dropper-rustic.png",
    "folder": "/punyakoti-taila/products/castor-oil",
    "filePath": "/punyakoti-taila/products/castor-oil/dropper-rustic.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/castor-oil/dropper-rustic.png",
    "width": 1024,
    "height": 1024,
    "alt": "castor-oil/dropper-rustic"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32423",
    "name": "hero-ayurvedic-tray.png",
    "folder": "/punyakoti-taila/products/castor-oil",
    "filePath": "/punyakoti-taila/products/castor-oil/hero-ayurvedic-tray.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/castor-oil/hero-ayurvedic-tray.png",
    "width": 1024,
    "height": 1024,
    "alt": "castor-oil/hero-ayurvedic-tray"
  },
  {
    "fileId": "6a140f015c7cd75eb8c31366",
    "name": "lifestyle-haircare.png",
    "folder": "/punyakoti-taila/products/castor-oil",
    "filePath": "/punyakoti-taila/products/castor-oil/lifestyle-haircare.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/castor-oil/lifestyle-haircare.png",
    "width": 1024,
    "height": 1024,
    "alt": "castor-oil/lifestyle-haircare"
  },
  {
    "fileId": "6a140f025c7cd75eb8c314f4",
    "name": "product-lineup-sizes.png",
    "folder": "/punyakoti-taila/products/castor-oil",
    "filePath": "/punyakoti-taila/products/castor-oil/product-lineup-sizes.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/castor-oil/product-lineup-sizes.png",
    "width": 1024,
    "height": 1024,
    "alt": "castor-oil/product-lineup-sizes"
  },
  {
    "fileId": "6a140f065c7cd75eb8c323c2",
    "name": "hero-jar-coconuts.png",
    "folder": "/punyakoti-taila/products/coconut-oil",
    "filePath": "/punyakoti-taila/products/coconut-oil/hero-jar-coconuts.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/coconut-oil/hero-jar-coconuts.png",
    "width": 1200,
    "height": 896,
    "alt": "coconut-oil/hero-jar-coconuts"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3248b",
    "name": "lifestyle-hand.png",
    "folder": "/punyakoti-taila/products/coconut-oil",
    "filePath": "/punyakoti-taila/products/coconut-oil/lifestyle-hand.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/coconut-oil/lifestyle-hand.png",
    "width": 1024,
    "height": 1024,
    "alt": "coconut-oil/lifestyle-hand"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3257c",
    "name": "natural-light-window.png",
    "folder": "/punyakoti-taila/products/coconut-oil",
    "filePath": "/punyakoti-taila/products/coconut-oil/natural-light-window.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/coconut-oil/natural-light-window.png",
    "width": 1024,
    "height": 1024,
    "alt": "coconut-oil/natural-light-window"
  },
  {
    "fileId": "6a2ae1dd5c7cd75eb8b69936",
    "name": "pour-into-cooking-pot-steaming.png",
    "folder": "/punyakoti-taila/products/coconut-oil",
    "filePath": "/punyakoti-taila/products/coconut-oil/pour-into-cooking-pot-steaming.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/coconut-oil/pour-into-cooking-pot-steaming.png",
    "width": 1264,
    "height": 848,
    "alt": "coconut-oil/pour-into-cooking-pot-steaming"
  },
  {
    "fileId": "6a2ae1df5c7cd75eb8b6a010",
    "name": "provenance-coconut-halves-jute.png",
    "folder": "/punyakoti-taila/products/coconut-oil",
    "filePath": "/punyakoti-taila/products/coconut-oil/provenance-coconut-halves-jute.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/coconut-oil/provenance-coconut-halves-jute.png",
    "width": 1264,
    "height": 848,
    "alt": "coconut-oil/provenance-coconut-halves-jute"
  },
  {
    "fileId": "6a140f015c7cd75eb8c313d5",
    "name": "texture-macro.png",
    "folder": "/punyakoti-taila/products/coconut-oil",
    "filePath": "/punyakoti-taila/products/coconut-oil/texture-macro.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/coconut-oil/texture-macro.png",
    "width": 1024,
    "height": 1024,
    "alt": "coconut-oil/texture-macro"
  },
  {
    "fileId": "6a140f025c7cd75eb8c3151a",
    "name": "wellness-spa.png",
    "folder": "/punyakoti-taila/products/coconut-oil",
    "filePath": "/punyakoti-taila/products/coconut-oil/wellness-spa.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/coconut-oil/wellness-spa.png",
    "width": 1024,
    "height": 1024,
    "alt": "coconut-oil/wellness-spa"
  },
  {
    "fileId": "6a140f015c7cd75eb8c3125c",
    "name": "collection-with-gomutra-ark.png",
    "folder": "/punyakoti-taila/products/dant-manjan",
    "filePath": "/punyakoti-taila/products/dant-manjan/collection-with-gomutra-ark.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/dant-manjan/collection-with-gomutra-ark.png",
    "width": 1200,
    "height": 896,
    "alt": "dant-manjan/collection-with-gomutra-ark"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32356",
    "name": "hero-jars-neem.png",
    "folder": "/punyakoti-taila/products/dant-manjan",
    "filePath": "/punyakoti-taila/products/dant-manjan/hero-jars-neem.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/dant-manjan/hero-jars-neem.png",
    "width": 1024,
    "height": 1024,
    "alt": "dant-manjan/hero-jars-neem"
  },
  {
    "fileId": "6a140f025c7cd75eb8c313f7",
    "name": "lifestyle-vanity.png",
    "folder": "/punyakoti-taila/products/dant-manjan",
    "filePath": "/punyakoti-taila/products/dant-manjan/lifestyle-vanity.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/dant-manjan/lifestyle-vanity.png",
    "width": 1200,
    "height": 896,
    "alt": "dant-manjan/lifestyle-vanity"
  },
  {
    "fileId": "6a140f055c7cd75eb8c320d6",
    "name": "hero-glass-jar.png",
    "folder": "/punyakoti-taila/products/dhoop-batti",
    "filePath": "/punyakoti-taila/products/dhoop-batti/hero-glass-jar.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/dhoop-batti/hero-glass-jar.png",
    "width": 1024,
    "height": 1024,
    "alt": "dhoop-batti/hero-glass-jar"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3242b",
    "name": "hero-tray-herbs.png",
    "folder": "/punyakoti-taila/products/gomutra-ark",
    "filePath": "/punyakoti-taila/products/gomutra-ark/hero-tray-herbs.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/gomutra-ark/hero-tray-herbs.png",
    "width": 1024,
    "height": 1024,
    "alt": "gomutra-ark/hero-tray-herbs"
  },
  {
    "fileId": "6a140f065c7cd75eb8c324b2",
    "name": "product-stone-herbs.png",
    "folder": "/punyakoti-taila/products/gomutra-ark",
    "filePath": "/punyakoti-taila/products/gomutra-ark/product-stone-herbs.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/gomutra-ark/product-stone-herbs.png",
    "width": 1024,
    "height": 1024,
    "alt": "gomutra-ark/product-stone-herbs"
  },
  {
    "fileId": "6a140f015c7cd75eb8c312ae",
    "name": "clean-white-marble.png",
    "folder": "/punyakoti-taila/products/groundnut-oil",
    "filePath": "/punyakoti-taila/products/groundnut-oil/clean-white-marble.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/groundnut-oil/clean-white-marble.png",
    "width": 1024,
    "height": 1024,
    "alt": "groundnut-oil/clean-white-marble"
  },
  {
    "fileId": "6a140f015c7cd75eb8c3136e",
    "name": "hero-cork-bottle.png",
    "folder": "/punyakoti-taila/products/groundnut-oil",
    "filePath": "/punyakoti-taila/products/groundnut-oil/hero-cork-bottle.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/groundnut-oil/hero-cork-bottle.png",
    "width": 1024,
    "height": 1024,
    "alt": "groundnut-oil/hero-cork-bottle"
  },
  {
    "fileId": "6a140f015c7cd75eb8c313c5",
    "name": "hero-stone-peanuts.png",
    "folder": "/punyakoti-taila/products/groundnut-oil",
    "filePath": "/punyakoti-taila/products/groundnut-oil/hero-stone-peanuts.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/groundnut-oil/hero-stone-peanuts.png",
    "width": 1200,
    "height": 896,
    "alt": "groundnut-oil/hero-stone-peanuts"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3255d",
    "name": "lifestyle-kitchen.png",
    "folder": "/punyakoti-taila/products/groundnut-oil",
    "filePath": "/punyakoti-taila/products/groundnut-oil/lifestyle-kitchen.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/groundnut-oil/lifestyle-kitchen.png",
    "width": 1024,
    "height": 1024,
    "alt": "groundnut-oil/lifestyle-kitchen"
  },
  {
    "fileId": "6a143bf55c7cd75eb802f044",
    "name": "ads.png",
    "folder": "/punyakoti-taila/products/real-photos",
    "filePath": "/punyakoti-taila/products/real-photos/ads.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/real-photos/ads.png",
    "width": 736,
    "height": 1062,
    "alt": "real-photos/ads"
  },
  {
    "fileId": "6a143bf75c7cd75eb8030967",
    "name": "amrut-drops.png",
    "folder": "/punyakoti-taila/products/real-photos",
    "filePath": "/punyakoti-taila/products/real-photos/amrut-drops.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/real-photos/amrut-drops.png",
    "width": 2060,
    "height": 1054,
    "alt": "real-photos/amrut-drops"
  },
  {
    "fileId": "6a143bf95c7cd75eb80325ff",
    "name": "dant-manjan.png",
    "folder": "/punyakoti-taila/products/real-photos",
    "filePath": "/punyakoti-taila/products/real-photos/dant-manjan.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/real-photos/dant-manjan.png",
    "width": 2056,
    "height": 932,
    "alt": "real-photos/dant-manjan"
  },
  {
    "fileId": "6a143bfb5c7cd75eb8034549",
    "name": "dhoops.png",
    "folder": "/punyakoti-taila/products/real-photos",
    "filePath": "/punyakoti-taila/products/real-photos/dhoops.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/real-photos/dhoops.png",
    "width": 2068,
    "height": 1028,
    "alt": "real-photos/dhoops"
  },
  {
    "fileId": "6a143bfd5c7cd75eb803640c",
    "name": "gomurtra-ark.png",
    "folder": "/punyakoti-taila/products/real-photos",
    "filePath": "/punyakoti-taila/products/real-photos/gomurtra-ark.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/real-photos/gomurtra-ark.png",
    "width": 1040,
    "height": 1134,
    "alt": "real-photos/gomurtra-ark"
  },
  {
    "fileId": "6a143bff5c7cd75eb8037ec0",
    "name": "machine-real.png",
    "folder": "/punyakoti-taila/products/real-photos",
    "filePath": "/punyakoti-taila/products/real-photos/machine-real.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/real-photos/machine-real.png",
    "width": 924,
    "height": 796,
    "alt": "real-photos/machine-real"
  },
  {
    "fileId": "6a143c015c7cd75eb8039c4f",
    "name": "mix-oil.png",
    "folder": "/punyakoti-taila/products/real-photos",
    "filePath": "/punyakoti-taila/products/real-photos/mix-oil.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/real-photos/mix-oil.png",
    "width": 1944,
    "height": 954,
    "alt": "real-photos/mix-oil"
  },
  {
    "fileId": "6a143c035c7cd75eb803bf7f",
    "name": "packed-boxes.png",
    "folder": "/punyakoti-taila/products/real-photos",
    "filePath": "/punyakoti-taila/products/real-photos/packed-boxes.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/real-photos/packed-boxes.png",
    "width": 2062,
    "height": 1004,
    "alt": "real-photos/packed-boxes"
  },
  {
    "fileId": "6a143c055c7cd75eb803e834",
    "name": "pickels.png",
    "folder": "/punyakoti-taila/products/real-photos",
    "filePath": "/punyakoti-taila/products/real-photos/pickels.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/real-photos/pickels.png",
    "width": 2072,
    "height": 998,
    "alt": "real-photos/pickels"
  },
  {
    "fileId": "6a143c075c7cd75eb804078f",
    "name": "shop-store.png",
    "folder": "/punyakoti-taila/products/real-photos",
    "filePath": "/punyakoti-taila/products/real-photos/shop-store.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/real-photos/shop-store.png",
    "width": 2028,
    "height": 966,
    "alt": "real-photos/shop-store"
  },
  {
    "fileId": "6a143c0a5c7cd75eb8042b42",
    "name": "shop.png",
    "folder": "/punyakoti-taila/products/real-photos",
    "filePath": "/punyakoti-taila/products/real-photos/shop.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/real-photos/shop.png",
    "width": 1832,
    "height": 896,
    "alt": "real-photos/shop"
  },
  {
    "fileId": "6a143c0c5c7cd75eb8044c98",
    "name": "small-packs.png",
    "folder": "/punyakoti-taila/products/real-photos",
    "filePath": "/punyakoti-taila/products/real-photos/small-packs.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/real-photos/small-packs.png",
    "width": 2080,
    "height": 940,
    "alt": "real-photos/small-packs"
  },
  {
    "fileId": "6a143c0e5c7cd75eb8046922",
    "name": "stores.png",
    "folder": "/punyakoti-taila/products/real-photos",
    "filePath": "/punyakoti-taila/products/real-photos/stores.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/real-photos/stores.png",
    "width": 1236,
    "height": 1182,
    "alt": "real-photos/stores"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32324",
    "name": "cinematic-drop-flower.png",
    "folder": "/punyakoti-taila/products/safflower-oil",
    "filePath": "/punyakoti-taila/products/safflower-oil/cinematic-drop-flower.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/safflower-oil/cinematic-drop-flower.png",
    "width": 1024,
    "height": 1024,
    "alt": "safflower-oil/cinematic-drop-flower"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3235b",
    "name": "hero-copper-drip.png",
    "folder": "/punyakoti-taila/products/safflower-oil",
    "filePath": "/punyakoti-taila/products/safflower-oil/hero-copper-drip.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/safflower-oil/hero-copper-drip.png",
    "width": 1200,
    "height": 896,
    "alt": "safflower-oil/hero-copper-drip"
  },
  {
    "fileId": "6a2ae1f05c7cd75eb8b6fa10",
    "name": "hero-safflower-field-sunset.png",
    "folder": "/punyakoti-taila/products/safflower-oil",
    "filePath": "/punyakoti-taila/products/safflower-oil/hero-safflower-field-sunset.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/safflower-oil/hero-safflower-field-sunset.png",
    "width": 1264,
    "height": 848,
    "alt": "safflower-oil/hero-safflower-field-sunset"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3244e",
    "name": "product-with-seeds.png",
    "folder": "/punyakoti-taila/products/safflower-oil",
    "filePath": "/punyakoti-taila/products/safflower-oil/product-with-seeds.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/safflower-oil/product-with-seeds.png",
    "width": 1024,
    "height": 1024,
    "alt": "safflower-oil/product-with-seeds"
  },
  {
    "fileId": "6a2ae1f45c7cd75eb8b70b48",
    "name": "sunflower-field-bottle-sunset.png",
    "folder": "/punyakoti-taila/products/safflower-oil",
    "filePath": "/punyakoti-taila/products/safflower-oil/sunflower-field-bottle-sunset.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/safflower-oil/sunflower-field-bottle-sunset.png",
    "width": 1024,
    "height": 1024,
    "alt": "safflower-oil/sunflower-field-bottle-sunset"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317d9",
    "name": "flat-lay-handmade-paper.png",
    "folder": "/punyakoti-taila/products/sesame-oil",
    "filePath": "/punyakoti-taila/products/sesame-oil/flat-lay-handmade-paper.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/sesame-oil/flat-lay-handmade-paper.png",
    "width": 1024,
    "height": 1024,
    "alt": "sesame-oil/flat-lay-handmade-paper"
  },
  {
    "fileId": "6a140f025c7cd75eb8c31546",
    "name": "heritage-dark-stone.png",
    "folder": "/punyakoti-taila/products/sesame-oil",
    "filePath": "/punyakoti-taila/products/sesame-oil/heritage-dark-stone.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/sesame-oil/heritage-dark-stone.png",
    "width": 1024,
    "height": 1024,
    "alt": "sesame-oil/heritage-dark-stone"
  },
  {
    "fileId": "6a140f035c7cd75eb8c318a7",
    "name": "hero-dark-moody.png",
    "folder": "/punyakoti-taila/products/sesame-oil",
    "filePath": "/punyakoti-taila/products/sesame-oil/hero-dark-moody.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/sesame-oil/hero-dark-moody.png",
    "width": 1024,
    "height": 1024,
    "alt": "sesame-oil/hero-dark-moody"
  },
  {
    "fileId": "6a2ae1f65c7cd75eb8b711fd",
    "name": "lifestyle-tray-brass-bell-jasmine.png",
    "folder": "/punyakoti-taila/products/sesame-oil",
    "filePath": "/punyakoti-taila/products/sesame-oil/lifestyle-tray-brass-bell-jasmine.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/sesame-oil/lifestyle-tray-brass-bell-jasmine.png",
    "width": 1264,
    "height": 848,
    "alt": "sesame-oil/lifestyle-tray-brass-bell-jasmine"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3245d",
    "name": "pour-brass-bowl-wide.png",
    "folder": "/punyakoti-taila/products/sesame-oil",
    "filePath": "/punyakoti-taila/products/sesame-oil/pour-brass-bowl-wide.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/sesame-oil/pour-brass-bowl-wide.png",
    "width": 1200,
    "height": 896,
    "alt": "sesame-oil/pour-brass-bowl-wide"
  },
  {
    "fileId": "6a140f015c7cd75eb8c313d0",
    "name": "pour-closeup.png",
    "folder": "/punyakoti-taila/products/sesame-oil",
    "filePath": "/punyakoti-taila/products/sesame-oil/pour-closeup.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/sesame-oil/pour-closeup.png",
    "width": 1024,
    "height": 1024,
    "alt": "sesame-oil/pour-closeup"
  },
  {
    "fileId": "6a1578cb5c7cd75eb801fc9e",
    "name": "seed-catalog-5-1200x630.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-5-1200x630.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-5-1200x630.jpg",
    "width": 1200,
    "height": 630,
    "alt": "punyakoti-taila/seed-catalog-5-1200x630"
  },
  {
    "fileId": "6a1578cb5c7cd75eb801fb82",
    "name": "seed-catalog-5-300x416.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-5-300x416.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-5-300x416.jpg",
    "width": 300,
    "height": 416,
    "alt": "punyakoti-taila/seed-catalog-5-300x416"
  },
  {
    "fileId": "6a1578cb5c7cd75eb801faa9",
    "name": "seed-catalog-5-500x500.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-5-500x500.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-5-500x500.jpg",
    "width": 500,
    "height": 500,
    "alt": "punyakoti-taila/seed-catalog-5-500x500"
  },
  {
    "fileId": "6a1578cb5c7cd75eb801fcd0",
    "name": "seed-catalog-5-600x833.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-5-600x833.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-5-600x833.jpg",
    "width": 600,
    "height": 833,
    "alt": "punyakoti-taila/seed-catalog-5-600x833"
  },
  {
    "fileId": "6a1578cb5c7cd75eb801fe1f",
    "name": "seed-catalog-5-900x1249.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-5-900x1249.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-5-900x1249.jpg",
    "width": 900,
    "height": 1249,
    "alt": "punyakoti-taila/seed-catalog-5-900x1249"
  },
  {
    "fileId": "6a1578cb5c7cd75eb801fff6",
    "name": "seed-catalog-5.jpeg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-5.jpeg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-5.jpeg",
    "width": 1200,
    "height": 1665,
    "alt": "punyakoti-taila/seed-catalog-5"
  },
  {
    "fileId": "6a1578cd5c7cd75eb80212f8",
    "name": "seed-catalog-6-1200x630.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-6-1200x630.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-6-1200x630.jpg",
    "width": 1200,
    "height": 630,
    "alt": "punyakoti-taila/seed-catalog-6-1200x630"
  },
  {
    "fileId": "6a1578cd5c7cd75eb802119e",
    "name": "seed-catalog-6-300x200.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-6-300x200.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-6-300x200.jpg",
    "width": 300,
    "height": 200,
    "alt": "punyakoti-taila/seed-catalog-6-300x200"
  },
  {
    "fileId": "6a1578cd5c7cd75eb8021210",
    "name": "seed-catalog-6-500x500.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-6-500x500.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-6-500x500.jpg",
    "width": 500,
    "height": 500,
    "alt": "punyakoti-taila/seed-catalog-6-500x500"
  },
  {
    "fileId": "6a1578cd5c7cd75eb802120f",
    "name": "seed-catalog-6-600x400.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-6-600x400.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-6-600x400.jpg",
    "width": 600,
    "height": 400,
    "alt": "punyakoti-taila/seed-catalog-6-600x400"
  },
  {
    "fileId": "6a1578cd5c7cd75eb8021305",
    "name": "seed-catalog-6-900x600.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-6-900x600.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-6-900x600.jpg",
    "width": 900,
    "height": 600,
    "alt": "punyakoti-taila/seed-catalog-6-900x600"
  },
  {
    "fileId": "6a1578cd5c7cd75eb802121d",
    "name": "seed-catalog-6.jpeg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-6.jpeg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-6.jpeg",
    "width": 1200,
    "height": 800,
    "alt": "punyakoti-taila/seed-catalog-6"
  },
  {
    "fileId": "6a1578cf5c7cd75eb8021e30",
    "name": "seed-catalog-7-1200x630.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-7-1200x630.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-7-1200x630.jpg",
    "width": 1200,
    "height": 630,
    "alt": "punyakoti-taila/seed-catalog-7-1200x630"
  },
  {
    "fileId": "6a1578cf5c7cd75eb8021ddc",
    "name": "seed-catalog-7-300x225.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-7-300x225.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-7-300x225.jpg",
    "width": 300,
    "height": 225,
    "alt": "punyakoti-taila/seed-catalog-7-300x225"
  },
  {
    "fileId": "6a1578d05c7cd75eb80220ab",
    "name": "seed-catalog-7-500x500.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-7-500x500.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-7-500x500.jpg",
    "width": 500,
    "height": 500,
    "alt": "punyakoti-taila/seed-catalog-7-500x500"
  },
  {
    "fileId": "6a1578cf5c7cd75eb8021e2b",
    "name": "seed-catalog-7-600x450.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-7-600x450.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-7-600x450.jpg",
    "width": 600,
    "height": 450,
    "alt": "punyakoti-taila/seed-catalog-7-600x450"
  },
  {
    "fileId": "6a1578cf5c7cd75eb8021dd8",
    "name": "seed-catalog-7-900x675.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-7-900x675.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-7-900x675.jpg",
    "width": 900,
    "height": 675,
    "alt": "punyakoti-taila/seed-catalog-7-900x675"
  },
  {
    "fileId": "6a1578cf5c7cd75eb8021e35",
    "name": "seed-catalog-7.jpeg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-7.jpeg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-7.jpeg",
    "width": 1200,
    "height": 900,
    "alt": "punyakoti-taila/seed-catalog-7"
  },
  {
    "fileId": "6a1578d15c7cd75eb80229c3",
    "name": "seed-catalog-8-1200x630.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-8-1200x630.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-8-1200x630.jpg",
    "width": 1200,
    "height": 630,
    "alt": "punyakoti-taila/seed-catalog-8-1200x630"
  },
  {
    "fileId": "6a1578d25c7cd75eb80229e5",
    "name": "seed-catalog-8-300x200.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-8-300x200.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-8-300x200.jpg",
    "width": 300,
    "height": 200,
    "alt": "punyakoti-taila/seed-catalog-8-300x200"
  },
  {
    "fileId": "6a1578d25c7cd75eb8022b24",
    "name": "seed-catalog-8-500x500.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-8-500x500.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-8-500x500.jpg",
    "width": 500,
    "height": 500,
    "alt": "punyakoti-taila/seed-catalog-8-500x500"
  },
  {
    "fileId": "6a1578d25c7cd75eb8022bce",
    "name": "seed-catalog-8-600x400.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-8-600x400.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-8-600x400.jpg",
    "width": 600,
    "height": 400,
    "alt": "punyakoti-taila/seed-catalog-8-600x400"
  },
  {
    "fileId": "6a1578d25c7cd75eb8022a5f",
    "name": "seed-catalog-8-900x600.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-8-900x600.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-8-900x600.jpg",
    "width": 900,
    "height": 600,
    "alt": "punyakoti-taila/seed-catalog-8-900x600"
  },
  {
    "fileId": "6a1578d25c7cd75eb8022d1f",
    "name": "seed-catalog-8.jpeg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-8.jpeg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-8.jpeg",
    "width": 1200,
    "height": 800,
    "alt": "punyakoti-taila/seed-catalog-8"
  },
  {
    "fileId": "6a1578d45c7cd75eb80234ba",
    "name": "seed-catalog-9-1200x630.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-9-1200x630.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-9-1200x630.jpg",
    "width": 1200,
    "height": 630,
    "alt": "punyakoti-taila/seed-catalog-9-1200x630"
  },
  {
    "fileId": "6a1578d45c7cd75eb8023485",
    "name": "seed-catalog-9-300x155.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-9-300x155.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-9-300x155.jpg",
    "width": 300,
    "height": 155,
    "alt": "punyakoti-taila/seed-catalog-9-300x155"
  },
  {
    "fileId": "6a1578d45c7cd75eb8023496",
    "name": "seed-catalog-9-500x500.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-9-500x500.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-9-500x500.jpg",
    "width": 500,
    "height": 500,
    "alt": "punyakoti-taila/seed-catalog-9-500x500"
  },
  {
    "fileId": "6a1578d45c7cd75eb80234f1",
    "name": "seed-catalog-9-600x310.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-9-600x310.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-9-600x310.jpg",
    "width": 600,
    "height": 310,
    "alt": "punyakoti-taila/seed-catalog-9-600x310"
  },
  {
    "fileId": "6a1578d45c7cd75eb80234c9",
    "name": "seed-catalog-9-900x465.jpg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-9-900x465.jpg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-9-900x465.jpg",
    "width": 900,
    "height": 465,
    "alt": "punyakoti-taila/seed-catalog-9-900x465"
  },
  {
    "fileId": "6a1578d45c7cd75eb8023516",
    "name": "seed-catalog-9.jpeg",
    "folder": "/punyakoti-taila",
    "filePath": "/punyakoti-taila/seed-catalog-9.jpeg",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/seed-catalog-9.jpeg",
    "width": 1200,
    "height": 620,
    "alt": "punyakoti-taila/seed-catalog-9"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317d3",
    "name": "boutique-dark-wood.png",
    "folder": "/punyakoti-taila/store",
    "filePath": "/punyakoti-taila/store/boutique-dark-wood.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/store/boutique-dark-wood.png",
    "width": 1376,
    "height": 768,
    "alt": "store/boutique-dark-wood"
  },
  {
    "fileId": "6a140f065c7cd75eb8c325e3",
    "name": "boutique-light-wood.png",
    "folder": "/punyakoti-taila/store",
    "filePath": "/punyakoti-taila/store/boutique-light-wood.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/store/boutique-light-wood.png",
    "width": 1200,
    "height": 896,
    "alt": "store/boutique-light-wood"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32524",
    "name": "boutique-modern-indian.png",
    "folder": "/punyakoti-taila/store",
    "filePath": "/punyakoti-taila/store/boutique-modern-indian.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/store/boutique-modern-indian.png",
    "width": 1024,
    "height": 1024,
    "alt": "store/boutique-modern-indian"
  },
  {
    "fileId": "6a140f055c7cd75eb8c31f75",
    "name": "account-dashboard.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/account-dashboard.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/account-dashboard.png",
    "width": 2560,
    "height": 3402,
    "alt": "ui-mockups/account-dashboard"
  },
  {
    "fileId": "6a140efd5c7cd75eb8c2f6c5",
    "name": "account-details.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/account-details.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/account-details.png",
    "width": 1320,
    "height": 1600,
    "alt": "ui-mockups/account-details"
  },
  {
    "fileId": "6a140efd5c7cd75eb8c2f76f",
    "name": "cart.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/cart.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/cart.png",
    "width": 1008,
    "height": 1600,
    "alt": "ui-mockups/cart"
  },
  {
    "fileId": "6a140efc5c7cd75eb8c2f4be",
    "name": "checkout.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/checkout.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/checkout.png",
    "width": 1057,
    "height": 1600,
    "alt": "ui-mockups/checkout"
  },
  {
    "fileId": "6a157adf5c7cd75eb80ffc14",
    "name": "plp_page.png",
    "folder": "/punyakoti-taila/ui-mockups/claude",
    "filePath": "/punyakoti-taila/ui-mockups/claude/plp_page.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/claude/plp_page.png",
    "width": 3024,
    "height": 5818,
    "alt": "claude/plp_page"
  },
  {
    "fileId": "6a140f015c7cd75eb8c31339",
    "name": "create-account.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/create-account.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/create-account.png",
    "width": 1600,
    "height": 1280,
    "alt": "ui-mockups/create-account"
  },
  {
    "fileId": "6a140efe5c7cd75eb8c2f9be",
    "name": "homepage.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/homepage.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/homepage.png",
    "width": 578,
    "height": 1600,
    "alt": "ui-mockups/homepage"
  },
  {
    "fileId": "6a140f005c7cd75eb8c3109b",
    "name": "login.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/login.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/login.png",
    "width": 1600,
    "height": 1280,
    "alt": "ui-mockups/login"
  },
  {
    "fileId": "6a140efd5c7cd75eb8c2f5c5",
    "name": "manage-addresses.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/manage-addresses.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/manage-addresses.png",
    "width": 1347,
    "height": 1600,
    "alt": "ui-mockups/manage-addresses"
  },
  {
    "fileId": "6a140efe5c7cd75eb8c2fb21",
    "name": "my-account.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/my-account.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/my-account.png",
    "width": 1457,
    "height": 1600,
    "alt": "ui-mockups/my-account"
  },
  {
    "fileId": "6a140efd5c7cd75eb8c2f645",
    "name": "order-confirmed.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/order-confirmed.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/order-confirmed.png",
    "width": 988,
    "height": 1600,
    "alt": "ui-mockups/order-confirmed"
  },
  {
    "fileId": "6a140efe5c7cd75eb8c2fa6a",
    "name": "product-detail-groundnut.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/product-detail-groundnut.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/product-detail-groundnut.png",
    "width": 1299,
    "height": 1600,
    "alt": "ui-mockups/product-detail-groundnut"
  },
  {
    "fileId": "6a140efe5c7cd75eb8c2fb5c",
    "name": "product-gallery.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/product-gallery.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/product-gallery.png",
    "width": 1144,
    "height": 1600,
    "alt": "ui-mockups/product-gallery"
  },
  {
    "fileId": "6a140efe5c7cd75eb8c2fa8a",
    "name": "search.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/search.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/search.png",
    "width": 1390,
    "height": 1600,
    "alt": "ui-mockups/search"
  },
  {
    "fileId": "6a140f015c7cd75eb8c311f3",
    "name": "shop-all.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/shop-all.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/shop-all.png",
    "width": 689,
    "height": 1600,
    "alt": "ui-mockups/shop-all"
  },
  {
    "fileId": "6a157ae25c7cd75eb8101a7d",
    "name": "account-dashboard.png",
    "folder": "/punyakoti-taila/ui-mockups/stitch",
    "filePath": "/punyakoti-taila/ui-mockups/stitch/account-dashboard.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/stitch/account-dashboard.png",
    "width": 2560,
    "height": 3402,
    "alt": "stitch/account-dashboard"
  },
  {
    "fileId": "6a157ae55c7cd75eb8103d2e",
    "name": "account-details.png",
    "folder": "/punyakoti-taila/ui-mockups/stitch",
    "filePath": "/punyakoti-taila/ui-mockups/stitch/account-details.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/stitch/account-details.png",
    "width": 1320,
    "height": 1600,
    "alt": "stitch/account-details"
  },
  {
    "fileId": "6a157ae75c7cd75eb8104a36",
    "name": "cart.png",
    "folder": "/punyakoti-taila/ui-mockups/stitch",
    "filePath": "/punyakoti-taila/ui-mockups/stitch/cart.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/stitch/cart.png",
    "width": 1008,
    "height": 1600,
    "alt": "stitch/cart"
  },
  {
    "fileId": "6a157ae95c7cd75eb81056cd",
    "name": "checkout.png",
    "folder": "/punyakoti-taila/ui-mockups/stitch",
    "filePath": "/punyakoti-taila/ui-mockups/stitch/checkout.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/stitch/checkout.png",
    "width": 1057,
    "height": 1600,
    "alt": "stitch/checkout"
  },
  {
    "fileId": "6a157aea5c7cd75eb8105e2a",
    "name": "create-account.png",
    "folder": "/punyakoti-taila/ui-mockups/stitch",
    "filePath": "/punyakoti-taila/ui-mockups/stitch/create-account.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/stitch/create-account.png",
    "width": 1600,
    "height": 1280,
    "alt": "stitch/create-account"
  },
  {
    "fileId": "6a157aec5c7cd75eb810664e",
    "name": "homepage.png",
    "folder": "/punyakoti-taila/ui-mockups/stitch",
    "filePath": "/punyakoti-taila/ui-mockups/stitch/homepage.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/stitch/homepage.png",
    "width": 578,
    "height": 1600,
    "alt": "stitch/homepage"
  },
  {
    "fileId": "6a157aee5c7cd75eb8106e2f",
    "name": "login.png",
    "folder": "/punyakoti-taila/ui-mockups/stitch",
    "filePath": "/punyakoti-taila/ui-mockups/stitch/login.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/stitch/login.png",
    "width": 1600,
    "height": 1280,
    "alt": "stitch/login"
  },
  {
    "fileId": "6a157aef5c7cd75eb8107558",
    "name": "manage-addresses.png",
    "folder": "/punyakoti-taila/ui-mockups/stitch",
    "filePath": "/punyakoti-taila/ui-mockups/stitch/manage-addresses.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/stitch/manage-addresses.png",
    "width": 1347,
    "height": 1600,
    "alt": "stitch/manage-addresses"
  },
  {
    "fileId": "6a157af15c7cd75eb8107da3",
    "name": "my-account.png",
    "folder": "/punyakoti-taila/ui-mockups/stitch",
    "filePath": "/punyakoti-taila/ui-mockups/stitch/my-account.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/stitch/my-account.png",
    "width": 1457,
    "height": 1600,
    "alt": "stitch/my-account"
  },
  {
    "fileId": "6a157af35c7cd75eb81085a1",
    "name": "order-confirmed.png",
    "folder": "/punyakoti-taila/ui-mockups/stitch",
    "filePath": "/punyakoti-taila/ui-mockups/stitch/order-confirmed.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/stitch/order-confirmed.png",
    "width": 988,
    "height": 1600,
    "alt": "stitch/order-confirmed"
  },
  {
    "fileId": "6a157af65c7cd75eb810a722",
    "name": "product-detail-groundnut.png",
    "folder": "/punyakoti-taila/ui-mockups/stitch",
    "filePath": "/punyakoti-taila/ui-mockups/stitch/product-detail-groundnut.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/stitch/product-detail-groundnut.png",
    "width": 1299,
    "height": 1600,
    "alt": "stitch/product-detail-groundnut"
  },
  {
    "fileId": "6a157af85c7cd75eb810b098",
    "name": "product-gallery.png",
    "folder": "/punyakoti-taila/ui-mockups/stitch",
    "filePath": "/punyakoti-taila/ui-mockups/stitch/product-gallery.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/stitch/product-gallery.png",
    "width": 1144,
    "height": 1600,
    "alt": "stitch/product-gallery"
  },
  {
    "fileId": "6a157afa5c7cd75eb810b8c5",
    "name": "search.png",
    "folder": "/punyakoti-taila/ui-mockups/stitch",
    "filePath": "/punyakoti-taila/ui-mockups/stitch/search.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/stitch/search.png",
    "width": 1390,
    "height": 1600,
    "alt": "stitch/search"
  },
  {
    "fileId": "6a157afc5c7cd75eb810c56d",
    "name": "shop-all.png",
    "folder": "/punyakoti-taila/ui-mockups/stitch",
    "filePath": "/punyakoti-taila/ui-mockups/stitch/shop-all.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/stitch/shop-all.png",
    "width": 689,
    "height": 1600,
    "alt": "stitch/shop-all"
  },
  {
    "fileId": "6a2ae2015c7cd75eb8b74c73",
    "name": "abhyanga-oil-massage-candles.png",
    "folder": "/punyakoti-taila/wellness",
    "filePath": "/punyakoti-taila/wellness/abhyanga-oil-massage-candles.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/wellness/abhyanga-oil-massage-candles.png",
    "width": 1024,
    "height": 1024,
    "alt": "wellness/abhyanga-oil-massage-candles"
  },
  {
    "fileId": "6a2ae2065c7cd75eb8b768d2",
    "name": "bathroom-stone-tray-bottle-towel.png",
    "folder": "/punyakoti-taila/wellness",
    "filePath": "/punyakoti-taila/wellness/bathroom-stone-tray-bottle-towel.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/wellness/bathroom-stone-tray-bottle-towel.png",
    "width": 1024,
    "height": 1024,
    "alt": "wellness/bathroom-stone-tray-bottle-towel"
  },
  {
    "fileId": "6a2ae2085c7cd75eb8b77281",
    "name": "child-dropper-bottle-herbs.png",
    "folder": "/punyakoti-taila/wellness",
    "filePath": "/punyakoti-taila/wellness/child-dropper-bottle-herbs.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/wellness/child-dropper-bottle-herbs.png",
    "width": 1264,
    "height": 848,
    "alt": "wellness/child-dropper-bottle-herbs"
  },
  {
    "fileId": "6a2ae20a5c7cd75eb8b77d4d",
    "name": "hands-oil-massage-marigold-flowers.png",
    "folder": "/punyakoti-taila/wellness",
    "filePath": "/punyakoti-taila/wellness/hands-oil-massage-marigold-flowers.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/wellness/hands-oil-massage-marigold-flowers.png",
    "width": 1024,
    "height": 1024,
    "alt": "wellness/hands-oil-massage-marigold-flowers"
  },
  {
    "fileId": "6a2ae20b5c7cd75eb8b78a90",
    "name": "meditation-woman-punyakoti-bottle.png",
    "folder": "/punyakoti-taila/wellness",
    "filePath": "/punyakoti-taila/wellness/meditation-woman-punyakoti-bottle.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/wellness/meditation-woman-punyakoti-bottle.png",
    "width": 1264,
    "height": 848,
    "alt": "wellness/meditation-woman-punyakoti-bottle"
  },
  {
    "fileId": "6a2ae20d5c7cd75eb8b79a81",
    "name": "nasya-dropper-copper-vessel-rustic-table.png",
    "folder": "/punyakoti-taila/wellness",
    "filePath": "/punyakoti-taila/wellness/nasya-dropper-copper-vessel-rustic-table.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/wellness/nasya-dropper-copper-vessel-rustic-table.png",
    "width": 1264,
    "height": 848,
    "alt": "wellness/nasya-dropper-copper-vessel-rustic-table"
  },
  {
    "fileId": "6a2ae20f5c7cd75eb8b7a619",
    "name": "nasya-dropper-plumeria-handmade-paper.png",
    "folder": "/punyakoti-taila/wellness",
    "filePath": "/punyakoti-taila/wellness/nasya-dropper-plumeria-handmade-paper.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/wellness/nasya-dropper-plumeria-handmade-paper.png",
    "width": 1024,
    "height": 1024,
    "alt": "wellness/nasya-dropper-plumeria-handmade-paper"
  },
  {
    "fileId": "6a2ae2105c7cd75eb8b7b0a4",
    "name": "spa-bathroom-bottle-lavender.png",
    "folder": "/punyakoti-taila/wellness",
    "filePath": "/punyakoti-taila/wellness/spa-bathroom-bottle-lavender.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/wellness/spa-bathroom-bottle-lavender.png",
    "width": 1264,
    "height": 848,
    "alt": "wellness/spa-bathroom-bottle-lavender"
  },
  {
    "fileId": "6a2ae2125c7cd75eb8b7bbdd",
    "name": "yoga-space-amber-bottle-incense.png",
    "folder": "/punyakoti-taila/wellness",
    "filePath": "/punyakoti-taila/wellness/yoga-space-amber-bottle-incense.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/wellness/yoga-space-amber-bottle-incense.png",
    "width": 1024,
    "height": 1024,
    "alt": "wellness/yoga-space-amber-bottle-incense"
  }
] as const
