// Auto-generated by scripts/listImageKit.ts — do not edit by hand.
// Re-run `pnpm imagekit:list` after uploading new assets to ImageKit.

export type ImageKitCatalogEntry = {
  fileId: string
  name: string
  folder: string
  filePath: string
  url: string
  width?: number
  height?: number
  alt: string
}

export const IMAGEKIT_ROOT = "/punyakoti-taila" as const

export const IMAGEKIT_FOLDERS: ReadonlyArray<{ folderPath: string; name: string }> = [
  {
    "folderPath": "/punyakoti-taila/brand",
    "name": "brand"
  },
  {
    "folderPath": "/punyakoti-taila/collections",
    "name": "collections"
  },
  {
    "folderPath": "/punyakoti-taila/gifting",
    "name": "gifting"
  },
  {
    "folderPath": "/punyakoti-taila/home",
    "name": "home"
  },
  {
    "folderPath": "/punyakoti-taila/ingredients",
    "name": "ingredients"
  },
  {
    "folderPath": "/punyakoti-taila/process",
    "name": "process"
  },
  {
    "folderPath": "/punyakoti-taila/products",
    "name": "products"
  },
  {
    "folderPath": "/punyakoti-taila/products/achaar-pickles",
    "name": "achaar-pickles"
  },
  {
    "folderPath": "/punyakoti-taila/products/almond-oil",
    "name": "almond-oil"
  },
  {
    "folderPath": "/punyakoti-taila/products/castor-oil",
    "name": "castor-oil"
  },
  {
    "folderPath": "/punyakoti-taila/products/coconut-oil",
    "name": "coconut-oil"
  },
  {
    "folderPath": "/punyakoti-taila/products/dant-manjan",
    "name": "dant-manjan"
  },
  {
    "folderPath": "/punyakoti-taila/products/dhoop-batti",
    "name": "dhoop-batti"
  },
  {
    "folderPath": "/punyakoti-taila/products/gomutra-ark",
    "name": "gomutra-ark"
  },
  {
    "folderPath": "/punyakoti-taila/products/groundnut-oil",
    "name": "groundnut-oil"
  },
  {
    "folderPath": "/punyakoti-taila/products/safflower-oil",
    "name": "safflower-oil"
  },
  {
    "folderPath": "/punyakoti-taila/products/sesame-oil",
    "name": "sesame-oil"
  },
  {
    "folderPath": "/punyakoti-taila/store",
    "name": "store"
  },
  {
    "folderPath": "/punyakoti-taila/ui-mockups",
    "name": "ui-mockups"
  }
] as const

export const IMAGEKIT_CATALOG: ReadonlyArray<ImageKitCatalogEntry> = [
  {
    "fileId": "6a140f025c7cd75eb8c315f1",
    "name": "logo-brand-sheet.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/logo-brand-sheet.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/logo-brand-sheet.png",
    "width": 1600,
    "height": 878,
    "alt": "brand/logo-brand-sheet"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317ae",
    "name": "logo-on-wood-press.png",
    "folder": "/punyakoti-taila/brand",
    "filePath": "/punyakoti-taila/brand/logo-on-wood-press.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/brand/logo-on-wood-press.png",
    "width": 1024,
    "height": 1024,
    "alt": "brand/logo-on-wood-press"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317bc",
    "name": "all-five-oils.png",
    "folder": "/punyakoti-taila/collections",
    "filePath": "/punyakoti-taila/collections/all-five-oils.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/collections/all-five-oils.png",
    "width": 1024,
    "height": 1024,
    "alt": "collections/all-five-oils"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317bf",
    "name": "dropper-trio-coconut-almond-sesame.png",
    "folder": "/punyakoti-taila/collections",
    "filePath": "/punyakoti-taila/collections/dropper-trio-coconut-almond-sesame.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/collections/dropper-trio-coconut-almond-sesame.png",
    "width": 1200,
    "height": 896,
    "alt": "collections/dropper-trio-coconut-almond-sesame"
  },
  {
    "fileId": "6a140f075c7cd75eb8c326cf",
    "name": "full-range-all-products.png",
    "folder": "/punyakoti-taila/collections",
    "filePath": "/punyakoti-taila/collections/full-range-all-products.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/collections/full-range-all-products.png",
    "width": 1693,
    "height": 929,
    "alt": "collections/full-range-all-products"
  },
  {
    "fileId": "6a140f075c7cd75eb8c326fe",
    "name": "full-range-large-bottles.png",
    "folder": "/punyakoti-taila/collections",
    "filePath": "/punyakoti-taila/collections/full-range-large-bottles.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/collections/full-range-large-bottles.png",
    "width": 1693,
    "height": 929,
    "alt": "collections/full-range-large-bottles"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317c8",
    "name": "three-bottles-row.png",
    "folder": "/punyakoti-taila/collections",
    "filePath": "/punyakoti-taila/collections/three-bottles-row.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/collections/three-bottles-row.png",
    "width": 1024,
    "height": 1024,
    "alt": "collections/three-bottles-row"
  },
  {
    "fileId": "6a140f025c7cd75eb8c31414",
    "name": "hero-unboxing.png",
    "folder": "/punyakoti-taila/gifting",
    "filePath": "/punyakoti-taila/gifting/hero-unboxing.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/gifting/hero-unboxing.png",
    "width": 1200,
    "height": 896,
    "alt": "gifting/hero-unboxing"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317ce",
    "name": "kraft-boxes-branded.png",
    "folder": "/punyakoti-taila/gifting",
    "filePath": "/punyakoti-taila/gifting/kraft-boxes-branded.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/gifting/kraft-boxes-branded.png",
    "width": 1200,
    "height": 896,
    "alt": "gifting/kraft-boxes-branded"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317b6",
    "name": "kraft-boxes-generic.png",
    "folder": "/punyakoti-taila/gifting",
    "filePath": "/punyakoti-taila/gifting/kraft-boxes-generic.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/gifting/kraft-boxes-generic.png",
    "width": 1024,
    "height": 1024,
    "alt": "gifting/kraft-boxes-generic"
  },
  {
    "fileId": "6a140f035c7cd75eb8c3189d",
    "name": "safflower-gift-box.png",
    "folder": "/punyakoti-taila/gifting",
    "filePath": "/punyakoti-taila/gifting/safflower-gift-box.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/gifting/safflower-gift-box.png",
    "width": 1024,
    "height": 1024,
    "alt": "gifting/safflower-gift-box"
  },
  {
    "fileId": "6a140f065c7cd75eb8c324d4",
    "name": "banner-ingredients-table.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/banner-ingredients-table.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/banner-ingredients-table.png",
    "width": 1024,
    "height": 1024,
    "alt": "home/banner-ingredients-table"
  },
  {
    "fileId": "6a140f035c7cd75eb8c319ce",
    "name": "banner-multi-panel.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/banner-multi-panel.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/banner-multi-panel.png",
    "width": 1536,
    "height": 1024,
    "alt": "home/banner-multi-panel"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32577",
    "name": "hero-01-ayurveda-bowl.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/hero-01-ayurveda-bowl.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/hero-01-ayurveda-bowl.png",
    "width": 1376,
    "height": 768,
    "alt": "home/hero-01-ayurveda-bowl"
  },
  {
    "fileId": "6a140f065c7cd75eb8c322ca",
    "name": "hero-02-product-range.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/hero-02-product-range.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/hero-02-product-range.png",
    "width": 1376,
    "height": 768,
    "alt": "home/hero-02-product-range"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317e9",
    "name": "hero-03-dropper-trio.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/hero-03-dropper-trio.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/hero-03-dropper-trio.png",
    "width": 1376,
    "height": 768,
    "alt": "home/hero-03-dropper-trio"
  },
  {
    "fileId": "6a140f065c7cd75eb8c325ca",
    "name": "hero-04-bottles-ingredients.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/hero-04-bottles-ingredients.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/hero-04-bottles-ingredients.png",
    "width": 1376,
    "height": 768,
    "alt": "home/hero-04-bottles-ingredients"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32611",
    "name": "hero-05-warm-golden-bottle.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/hero-05-warm-golden-bottle.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/hero-05-warm-golden-bottle.png",
    "width": 1717,
    "height": 916,
    "alt": "home/hero-05-warm-golden-bottle"
  },
  {
    "fileId": "6a140f035c7cd75eb8c319e3",
    "name": "hero-06-branded-box-bottle.png",
    "folder": "/punyakoti-taila/home",
    "filePath": "/punyakoti-taila/home/hero-06-branded-box-bottle.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/home/hero-06-branded-box-bottle.png",
    "width": 1536,
    "height": 1024,
    "alt": "home/hero-06-branded-box-bottle"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32510",
    "name": "mortar-pestle-filling.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/mortar-pestle-filling.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/mortar-pestle-filling.png",
    "width": 1376,
    "height": 768,
    "alt": "ingredients/mortar-pestle-filling"
  },
  {
    "fileId": "6a140f015c7cd75eb8c312cd",
    "name": "oil-ripples-wooden-bowl.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/oil-ripples-wooden-bowl.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/oil-ripples-wooden-bowl.png",
    "width": 1024,
    "height": 1024,
    "alt": "ingredients/oil-ripples-wooden-bowl"
  },
  {
    "fileId": "6a140f025c7cd75eb8c31774",
    "name": "raw-seeds-peanuts-coconut.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/raw-seeds-peanuts-coconut.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/raw-seeds-peanuts-coconut.png",
    "width": 1024,
    "height": 1024,
    "alt": "ingredients/raw-seeds-peanuts-coconut"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3249c",
    "name": "spoon-oil-logo-closeup.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/spoon-oil-logo-closeup.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/spoon-oil-logo-closeup.png",
    "width": 1200,
    "height": 896,
    "alt": "ingredients/spoon-oil-logo-closeup"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317cd",
    "name": "spoon-oil-over-peanuts.png",
    "folder": "/punyakoti-taila/ingredients",
    "filePath": "/punyakoti-taila/ingredients/spoon-oil-over-peanuts.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ingredients/spoon-oil-over-peanuts.png",
    "width": 1024,
    "height": 1024,
    "alt": "ingredients/spoon-oil-over-peanuts"
  },
  {
    "fileId": "6a140f065c7cd75eb8c325a9",
    "name": "ghana-press-oil-flowing.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/ghana-press-oil-flowing.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/ghana-press-oil-flowing.png",
    "width": 1024,
    "height": 1024,
    "alt": "process/ghana-press-oil-flowing"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32566",
    "name": "ghana-press-rustic.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/ghana-press-rustic.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/ghana-press-rustic.png",
    "width": 1024,
    "height": 1024,
    "alt": "process/ghana-press-rustic"
  },
  {
    "fileId": "6a140f025c7cd75eb8c315ac",
    "name": "ghana-press-studio.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/ghana-press-studio.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/ghana-press-studio.png",
    "width": 1200,
    "height": 896,
    "alt": "process/ghana-press-studio"
  },
  {
    "fileId": "6a140f035c7cd75eb8c31877",
    "name": "traditional-ghani-village.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/traditional-ghani-village.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/traditional-ghani-village.png",
    "width": 1024,
    "height": 1024,
    "alt": "process/traditional-ghani-village"
  },
  {
    "fileId": "6a140f035c7cd75eb8c31bbc",
    "name": "wood-press-machine-branded.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/wood-press-machine-branded.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/wood-press-machine-branded.png",
    "width": 1706,
    "height": 922,
    "alt": "process/wood-press-machine-branded"
  },
  {
    "fileId": "6a140f035c7cd75eb8c319b8",
    "name": "wood-press-machine-moody.png",
    "folder": "/punyakoti-taila/process",
    "filePath": "/punyakoti-taila/process/wood-press-machine-moody.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/process/wood-press-machine-moody.png",
    "width": 1672,
    "height": 941,
    "alt": "process/wood-press-machine-moody"
  },
  {
    "fileId": "6a140f065c7cd75eb8c323da",
    "name": "hero-branded-jars.png",
    "folder": "/punyakoti-taila/products/achaar-pickles",
    "filePath": "/punyakoti-taila/products/achaar-pickles/hero-branded-jars.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/achaar-pickles/hero-branded-jars.png",
    "width": 1200,
    "height": 896,
    "alt": "achaar-pickles/hero-branded-jars"
  },
  {
    "fileId": "6a140f065c7cd75eb8c323a3",
    "name": "rustic-yellow-cap-jars.png",
    "folder": "/punyakoti-taila/products/achaar-pickles",
    "filePath": "/punyakoti-taila/products/achaar-pickles/rustic-yellow-cap-jars.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/achaar-pickles/rustic-yellow-cap-jars.png",
    "width": 1024,
    "height": 1024,
    "alt": "achaar-pickles/rustic-yellow-cap-jars"
  },
  {
    "fileId": "6a140f025c7cd75eb8c3145d",
    "name": "hero-dropper.png",
    "folder": "/punyakoti-taila/products/almond-oil",
    "filePath": "/punyakoti-taila/products/almond-oil/hero-dropper.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/almond-oil/hero-dropper.png",
    "width": 1024,
    "height": 1024,
    "alt": "almond-oil/hero-dropper"
  },
  {
    "fileId": "6a140f055c7cd75eb8c321d6",
    "name": "dropper-rustic.png",
    "folder": "/punyakoti-taila/products/castor-oil",
    "filePath": "/punyakoti-taila/products/castor-oil/dropper-rustic.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/castor-oil/dropper-rustic.png",
    "width": 1024,
    "height": 1024,
    "alt": "castor-oil/dropper-rustic"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32423",
    "name": "hero-ayurvedic-tray.png",
    "folder": "/punyakoti-taila/products/castor-oil",
    "filePath": "/punyakoti-taila/products/castor-oil/hero-ayurvedic-tray.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/castor-oil/hero-ayurvedic-tray.png",
    "width": 1024,
    "height": 1024,
    "alt": "castor-oil/hero-ayurvedic-tray"
  },
  {
    "fileId": "6a140f015c7cd75eb8c31366",
    "name": "lifestyle-haircare.png",
    "folder": "/punyakoti-taila/products/castor-oil",
    "filePath": "/punyakoti-taila/products/castor-oil/lifestyle-haircare.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/castor-oil/lifestyle-haircare.png",
    "width": 1024,
    "height": 1024,
    "alt": "castor-oil/lifestyle-haircare"
  },
  {
    "fileId": "6a140f025c7cd75eb8c314f4",
    "name": "product-lineup-sizes.png",
    "folder": "/punyakoti-taila/products/castor-oil",
    "filePath": "/punyakoti-taila/products/castor-oil/product-lineup-sizes.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/castor-oil/product-lineup-sizes.png",
    "width": 1024,
    "height": 1024,
    "alt": "castor-oil/product-lineup-sizes"
  },
  {
    "fileId": "6a140f065c7cd75eb8c323c2",
    "name": "hero-jar-coconuts.png",
    "folder": "/punyakoti-taila/products/coconut-oil",
    "filePath": "/punyakoti-taila/products/coconut-oil/hero-jar-coconuts.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/coconut-oil/hero-jar-coconuts.png",
    "width": 1200,
    "height": 896,
    "alt": "coconut-oil/hero-jar-coconuts"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3248b",
    "name": "lifestyle-hand.png",
    "folder": "/punyakoti-taila/products/coconut-oil",
    "filePath": "/punyakoti-taila/products/coconut-oil/lifestyle-hand.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/coconut-oil/lifestyle-hand.png",
    "width": 1024,
    "height": 1024,
    "alt": "coconut-oil/lifestyle-hand"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3257c",
    "name": "natural-light-window.png",
    "folder": "/punyakoti-taila/products/coconut-oil",
    "filePath": "/punyakoti-taila/products/coconut-oil/natural-light-window.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/coconut-oil/natural-light-window.png",
    "width": 1024,
    "height": 1024,
    "alt": "coconut-oil/natural-light-window"
  },
  {
    "fileId": "6a140f015c7cd75eb8c313d5",
    "name": "texture-macro.png",
    "folder": "/punyakoti-taila/products/coconut-oil",
    "filePath": "/punyakoti-taila/products/coconut-oil/texture-macro.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/coconut-oil/texture-macro.png",
    "width": 1024,
    "height": 1024,
    "alt": "coconut-oil/texture-macro"
  },
  {
    "fileId": "6a140f025c7cd75eb8c3151a",
    "name": "wellness-spa.png",
    "folder": "/punyakoti-taila/products/coconut-oil",
    "filePath": "/punyakoti-taila/products/coconut-oil/wellness-spa.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/coconut-oil/wellness-spa.png",
    "width": 1024,
    "height": 1024,
    "alt": "coconut-oil/wellness-spa"
  },
  {
    "fileId": "6a140f015c7cd75eb8c3125c",
    "name": "collection-with-gomutra-ark.png",
    "folder": "/punyakoti-taila/products/dant-manjan",
    "filePath": "/punyakoti-taila/products/dant-manjan/collection-with-gomutra-ark.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/dant-manjan/collection-with-gomutra-ark.png",
    "width": 1200,
    "height": 896,
    "alt": "dant-manjan/collection-with-gomutra-ark"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32356",
    "name": "hero-jars-neem.png",
    "folder": "/punyakoti-taila/products/dant-manjan",
    "filePath": "/punyakoti-taila/products/dant-manjan/hero-jars-neem.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/dant-manjan/hero-jars-neem.png",
    "width": 1024,
    "height": 1024,
    "alt": "dant-manjan/hero-jars-neem"
  },
  {
    "fileId": "6a140f025c7cd75eb8c313f7",
    "name": "lifestyle-vanity.png",
    "folder": "/punyakoti-taila/products/dant-manjan",
    "filePath": "/punyakoti-taila/products/dant-manjan/lifestyle-vanity.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/dant-manjan/lifestyle-vanity.png",
    "width": 1200,
    "height": 896,
    "alt": "dant-manjan/lifestyle-vanity"
  },
  {
    "fileId": "6a140f055c7cd75eb8c320d6",
    "name": "hero-glass-jar.png",
    "folder": "/punyakoti-taila/products/dhoop-batti",
    "filePath": "/punyakoti-taila/products/dhoop-batti/hero-glass-jar.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/dhoop-batti/hero-glass-jar.png",
    "width": 1024,
    "height": 1024,
    "alt": "dhoop-batti/hero-glass-jar"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3242b",
    "name": "hero-tray-herbs.png",
    "folder": "/punyakoti-taila/products/gomutra-ark",
    "filePath": "/punyakoti-taila/products/gomutra-ark/hero-tray-herbs.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/gomutra-ark/hero-tray-herbs.png",
    "width": 1024,
    "height": 1024,
    "alt": "gomutra-ark/hero-tray-herbs"
  },
  {
    "fileId": "6a140f065c7cd75eb8c324b2",
    "name": "product-stone-herbs.png",
    "folder": "/punyakoti-taila/products/gomutra-ark",
    "filePath": "/punyakoti-taila/products/gomutra-ark/product-stone-herbs.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/gomutra-ark/product-stone-herbs.png",
    "width": 1024,
    "height": 1024,
    "alt": "gomutra-ark/product-stone-herbs"
  },
  {
    "fileId": "6a140f015c7cd75eb8c312ae",
    "name": "clean-white-marble.png",
    "folder": "/punyakoti-taila/products/groundnut-oil",
    "filePath": "/punyakoti-taila/products/groundnut-oil/clean-white-marble.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/groundnut-oil/clean-white-marble.png",
    "width": 1024,
    "height": 1024,
    "alt": "groundnut-oil/clean-white-marble"
  },
  {
    "fileId": "6a140f015c7cd75eb8c3136e",
    "name": "hero-cork-bottle.png",
    "folder": "/punyakoti-taila/products/groundnut-oil",
    "filePath": "/punyakoti-taila/products/groundnut-oil/hero-cork-bottle.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/groundnut-oil/hero-cork-bottle.png",
    "width": 1024,
    "height": 1024,
    "alt": "groundnut-oil/hero-cork-bottle"
  },
  {
    "fileId": "6a140f015c7cd75eb8c313c5",
    "name": "hero-stone-peanuts.png",
    "folder": "/punyakoti-taila/products/groundnut-oil",
    "filePath": "/punyakoti-taila/products/groundnut-oil/hero-stone-peanuts.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/groundnut-oil/hero-stone-peanuts.png",
    "width": 1200,
    "height": 896,
    "alt": "groundnut-oil/hero-stone-peanuts"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3255d",
    "name": "lifestyle-kitchen.png",
    "folder": "/punyakoti-taila/products/groundnut-oil",
    "filePath": "/punyakoti-taila/products/groundnut-oil/lifestyle-kitchen.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/groundnut-oil/lifestyle-kitchen.png",
    "width": 1024,
    "height": 1024,
    "alt": "groundnut-oil/lifestyle-kitchen"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32324",
    "name": "cinematic-drop-flower.png",
    "folder": "/punyakoti-taila/products/safflower-oil",
    "filePath": "/punyakoti-taila/products/safflower-oil/cinematic-drop-flower.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/safflower-oil/cinematic-drop-flower.png",
    "width": 1024,
    "height": 1024,
    "alt": "safflower-oil/cinematic-drop-flower"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3235b",
    "name": "hero-copper-drip.png",
    "folder": "/punyakoti-taila/products/safflower-oil",
    "filePath": "/punyakoti-taila/products/safflower-oil/hero-copper-drip.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/safflower-oil/hero-copper-drip.png",
    "width": 1200,
    "height": 896,
    "alt": "safflower-oil/hero-copper-drip"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3244e",
    "name": "product-with-seeds.png",
    "folder": "/punyakoti-taila/products/safflower-oil",
    "filePath": "/punyakoti-taila/products/safflower-oil/product-with-seeds.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/safflower-oil/product-with-seeds.png",
    "width": 1024,
    "height": 1024,
    "alt": "safflower-oil/product-with-seeds"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317d9",
    "name": "flat-lay-handmade-paper.png",
    "folder": "/punyakoti-taila/products/sesame-oil",
    "filePath": "/punyakoti-taila/products/sesame-oil/flat-lay-handmade-paper.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/sesame-oil/flat-lay-handmade-paper.png",
    "width": 1024,
    "height": 1024,
    "alt": "sesame-oil/flat-lay-handmade-paper"
  },
  {
    "fileId": "6a140f025c7cd75eb8c31546",
    "name": "heritage-dark-stone.png",
    "folder": "/punyakoti-taila/products/sesame-oil",
    "filePath": "/punyakoti-taila/products/sesame-oil/heritage-dark-stone.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/sesame-oil/heritage-dark-stone.png",
    "width": 1024,
    "height": 1024,
    "alt": "sesame-oil/heritage-dark-stone"
  },
  {
    "fileId": "6a140f035c7cd75eb8c318a7",
    "name": "hero-dark-moody.png",
    "folder": "/punyakoti-taila/products/sesame-oil",
    "filePath": "/punyakoti-taila/products/sesame-oil/hero-dark-moody.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/sesame-oil/hero-dark-moody.png",
    "width": 1024,
    "height": 1024,
    "alt": "sesame-oil/hero-dark-moody"
  },
  {
    "fileId": "6a140f065c7cd75eb8c3245d",
    "name": "pour-brass-bowl-wide.png",
    "folder": "/punyakoti-taila/products/sesame-oil",
    "filePath": "/punyakoti-taila/products/sesame-oil/pour-brass-bowl-wide.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/sesame-oil/pour-brass-bowl-wide.png",
    "width": 1200,
    "height": 896,
    "alt": "sesame-oil/pour-brass-bowl-wide"
  },
  {
    "fileId": "6a140f015c7cd75eb8c313d0",
    "name": "pour-closeup.png",
    "folder": "/punyakoti-taila/products/sesame-oil",
    "filePath": "/punyakoti-taila/products/sesame-oil/pour-closeup.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/products/sesame-oil/pour-closeup.png",
    "width": 1024,
    "height": 1024,
    "alt": "sesame-oil/pour-closeup"
  },
  {
    "fileId": "6a140f025c7cd75eb8c317d3",
    "name": "boutique-dark-wood.png",
    "folder": "/punyakoti-taila/store",
    "filePath": "/punyakoti-taila/store/boutique-dark-wood.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/store/boutique-dark-wood.png",
    "width": 1376,
    "height": 768,
    "alt": "store/boutique-dark-wood"
  },
  {
    "fileId": "6a140f065c7cd75eb8c325e3",
    "name": "boutique-light-wood.png",
    "folder": "/punyakoti-taila/store",
    "filePath": "/punyakoti-taila/store/boutique-light-wood.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/store/boutique-light-wood.png",
    "width": 1200,
    "height": 896,
    "alt": "store/boutique-light-wood"
  },
  {
    "fileId": "6a140f065c7cd75eb8c32524",
    "name": "boutique-modern-indian.png",
    "folder": "/punyakoti-taila/store",
    "filePath": "/punyakoti-taila/store/boutique-modern-indian.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/store/boutique-modern-indian.png",
    "width": 1024,
    "height": 1024,
    "alt": "store/boutique-modern-indian"
  },
  {
    "fileId": "6a140f055c7cd75eb8c31f75",
    "name": "account-dashboard.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/account-dashboard.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/account-dashboard.png",
    "width": 2560,
    "height": 3402,
    "alt": "ui-mockups/account-dashboard"
  },
  {
    "fileId": "6a140efd5c7cd75eb8c2f6c5",
    "name": "account-details.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/account-details.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/account-details.png",
    "width": 1320,
    "height": 1600,
    "alt": "ui-mockups/account-details"
  },
  {
    "fileId": "6a140efd5c7cd75eb8c2f76f",
    "name": "cart.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/cart.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/cart.png",
    "width": 1008,
    "height": 1600,
    "alt": "ui-mockups/cart"
  },
  {
    "fileId": "6a140efc5c7cd75eb8c2f4be",
    "name": "checkout.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/checkout.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/checkout.png",
    "width": 1057,
    "height": 1600,
    "alt": "ui-mockups/checkout"
  },
  {
    "fileId": "6a140f015c7cd75eb8c31339",
    "name": "create-account.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/create-account.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/create-account.png",
    "width": 1600,
    "height": 1280,
    "alt": "ui-mockups/create-account"
  },
  {
    "fileId": "6a140efe5c7cd75eb8c2f9be",
    "name": "homepage.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/homepage.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/homepage.png",
    "width": 578,
    "height": 1600,
    "alt": "ui-mockups/homepage"
  },
  {
    "fileId": "6a140f005c7cd75eb8c3109b",
    "name": "login.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/login.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/login.png",
    "width": 1600,
    "height": 1280,
    "alt": "ui-mockups/login"
  },
  {
    "fileId": "6a140efd5c7cd75eb8c2f5c5",
    "name": "manage-addresses.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/manage-addresses.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/manage-addresses.png",
    "width": 1347,
    "height": 1600,
    "alt": "ui-mockups/manage-addresses"
  },
  {
    "fileId": "6a140efe5c7cd75eb8c2fb21",
    "name": "my-account.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/my-account.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/my-account.png",
    "width": 1457,
    "height": 1600,
    "alt": "ui-mockups/my-account"
  },
  {
    "fileId": "6a140efd5c7cd75eb8c2f645",
    "name": "order-confirmed.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/order-confirmed.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/order-confirmed.png",
    "width": 988,
    "height": 1600,
    "alt": "ui-mockups/order-confirmed"
  },
  {
    "fileId": "6a140efe5c7cd75eb8c2fa6a",
    "name": "product-detail-groundnut.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/product-detail-groundnut.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/product-detail-groundnut.png",
    "width": 1299,
    "height": 1600,
    "alt": "ui-mockups/product-detail-groundnut"
  },
  {
    "fileId": "6a140efe5c7cd75eb8c2fb5c",
    "name": "product-gallery.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/product-gallery.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/product-gallery.png",
    "width": 1144,
    "height": 1600,
    "alt": "ui-mockups/product-gallery"
  },
  {
    "fileId": "6a140efe5c7cd75eb8c2fa8a",
    "name": "search.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/search.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/search.png",
    "width": 1390,
    "height": 1600,
    "alt": "ui-mockups/search"
  },
  {
    "fileId": "6a140f015c7cd75eb8c311f3",
    "name": "shop-all.png",
    "folder": "/punyakoti-taila/ui-mockups",
    "filePath": "/punyakoti-taila/ui-mockups/shop-all.png",
    "url": "https://ik.imagekit.io/zx7l7bhei/punyakoti-taila/ui-mockups/shop-all.png",
    "width": 689,
    "height": 1600,
    "alt": "ui-mockups/shop-all"
  }
] as const
