#!/usr/bin/env tsx
/**
 * Walk the ImageKit account under $IMAGEKIT_FOLDER and write
 * src/seed/imagekitCatalog.generated.ts with one entry per file:
 *   { fileId, name, folder, filePath, url, alt }
 *
 * `alt` is derived from `<folder-leaf>/<filename-without-ext>` so it is stable
 * across re-runs (the seed pipeline uses `alt` to dedupe).
 *
 * Run: `pnpm imagekit:list` (added to package.json).
 */
import 'dotenv/config'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { listAllImageKitAssets, type ImageKitFile, type ImageKitFolder } from '../src/lib/imagekit/listAll'
import { getImageKitRoot } from '../src/lib/imagekit/client'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

function altFor(file: ImageKitFile): string {
  const stem = file.name.replace(/\.[a-z0-9]+$/i, '')
  const folderLeaf = file.folder.split('/').filter(Boolean).pop() || 'root'
  return `${folderLeaf}/${stem}`
}

function repoRoot(): string {
  return path.resolve(__dirname, '..')
}

async function main() {
  const root = getImageKitRoot()
  console.log(`[imagekit:list] crawling ${root} ...`)
  const { folders, files } = await listAllImageKitAssets(root)
  console.log(`[imagekit:list] found ${folders.length} folders, ${files.length} files`)

  const entries = files
    .map((f) => ({
      fileId: f.fileId,
      name: f.name,
      folder: f.folder,
      filePath: f.filePath,
      url: f.url,
      width: f.width,
      height: f.height,
      alt: altFor(f),
    }))
    .sort((a, b) => a.filePath.localeCompare(b.filePath))

  const folderList: ImageKitFolder[] = folders
    .slice()
    .sort((a, b) => a.folderPath.localeCompare(b.folderPath))

  const out =
    '// Auto-generated by scripts/listImageKit.ts — do not edit by hand.\n' +
    '// Re-run `pnpm imagekit:list` after uploading new assets to ImageKit.\n\n' +
    'export type ImageKitCatalogEntry = {\n' +
    '  fileId: string\n' +
    '  name: string\n' +
    '  folder: string\n' +
    '  filePath: string\n' +
    '  url: string\n' +
    '  width?: number\n' +
    '  height?: number\n' +
    '  alt: string\n' +
    '}\n\n' +
    `export const IMAGEKIT_ROOT = ${JSON.stringify(root)} as const\n\n` +
    `export const IMAGEKIT_FOLDERS: ReadonlyArray<{ folderPath: string; name: string }> = ${JSON.stringify(folderList, null, 2)} as const\n\n` +
    `export const IMAGEKIT_CATALOG: ReadonlyArray<ImageKitCatalogEntry> = ${JSON.stringify(entries, null, 2)} as const\n`

  const outPath = path.join(repoRoot(), 'src/seed/imagekitCatalog.generated.ts')
  await fs.mkdir(path.dirname(outPath), { recursive: true })
  await fs.writeFile(outPath, out, 'utf8')
  console.log(`[imagekit:list] wrote ${outPath}`)
}

main().catch((err) => {
  console.error('[imagekit:list] failed:', err)
  process.exit(1)
})
