/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    products: Product;
    orders: Order;
    reviews: Review;
    testimonials: Testimonial;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'homepage-settings': HomepageSetting;
    'shop-listing': ShopListing;
    'product-detail': ProductDetail;
    cart: Cart;
    account: Account;
    'order-success': OrderSuccess;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'homepage-settings': HomepageSettingsSelect<false> | HomepageSettingsSelect<true>;
    'shop-listing': ShopListingSelect<false> | ShopListingSelect<true>;
    'product-detail': ProductDetailSelect<false> | ProductDetailSelect<true>;
    cart: CartSelect<false> | CartSelect<true>;
    account: AccountSelect<false> | AccountSelect<true>;
    'order-success': OrderSuccessSelect<false> | OrderSuccessSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | {
        eyebrow?: string | null;
        headlineLine1?: string | null;
        headlineLine2?: string | null;
        /**
         * Must match a word in line 2 exactly — shown in italic mustard gold
         */
        headlineItalicWord?: string | null;
        body?: string | null;
        primaryCTA?: {
          label?: string | null;
          href?: string | null;
        };
        secondaryCTA?: {
          label?: string | null;
          href?: string | null;
        };
        reviewRating?: string | null;
        reviewCount?: string | null;
        backgroundStyle?: ('cream' | 'dark-green' | 'warm-white') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ptHeroSection';
      }
    | {
        items?:
          | {
              icon: 'leaf' | 'drop' | 'truck' | 'shield' | 'star' | 'check';
              label: string;
              sub?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ptTrustStrip';
      }
    | {
        eyebrow?: string | null;
        headline?: string | null;
        body?: string | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        /**
         * Select up to 6 products to feature. Only published products appear on the site.
         */
        products?: (number | Product)[] | null;
        columns?: ('2' | '3' | '4') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ptFeaturedProducts';
      }
    | {
        eyebrow?: string | null;
        headlineLine1?: string | null;
        headlineLine2?: string | null;
        body?: string | null;
        stats?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ptProcessBanner';
      }
    | {
        eyebrow?: string | null;
        headline?: string | null;
        /**
         * Must be an exact substring of Headline above
         */
        headlineItalic?: string | null;
        cards?:
          | {
              icon: 'leaf' | 'drop' | 'shield' | 'star' | 'check';
              title: string;
              body: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ptBenefitCards';
      }
    | {
        eyebrow?: string | null;
        headline?: string | null;
        source?: ('featured' | 'manual') | null;
        /**
         * Only used when source is set to "Manual"
         */
        manualItems?:
          | {
              customerName: string;
              customerLocation?: string | null;
              /**
               * Optional — auto from name if empty
               */
              initials?: string | null;
              rating?: number | null;
              title?: string | null;
              body: string;
              id?: string | null;
            }[]
          | null;
        maxItems?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ptTestimonialsSection';
      }
    | {
        headline?: string | null;
        body?: string | null;
        legalText?: string | null;
        buttonLabel?: string | null;
        style?: ('dark-green' | 'cream' | 'mustard') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ptNewsletterBand';
      }
    | {
        eyebrow?: string | null;
        headline?: string | null;
        items?:
          | {
              question: string;
              answer: string;
              id?: string | null;
            }[]
          | null;
        style?: ('light' | 'dark') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ptFAQSection';
      }
    | {
        icon?: ('drop' | 'leaf' | 'cart' | 'user' | 'package' | 'search' | 'shield') | null;
        headline: string;
        body?: string | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        /**
         * Describe what this page section is for (admin only reference)
         */
        note?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ptEmptyState';
      }
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  /**
   * Sub-folder under /punyakoti-taila. Type a new name to create it on upload. Existing: brand, collections, gifting, home, ingredients, process, products, products/achaar-pickles, products/almond-oil, products/castor-oil, products/coconut-oil, products/dant-manjan, products/dhoop-batti, products/gomutra-ark, products/groundnut-oil, products/safflower-oil, products/sesame-oil, store, ui-mockups
   */
  imagekitFolder?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * ImageKit fileId.
   */
  imagekitFileId?: string | null;
  imagekitFilePath?: string | null;
  imagekitUrl?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      /**
       * ImageKit fileId.
       */
      imagekitFileId?: string | null;
      imagekitFilePath?: string | null;
      imagekitUrl?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      /**
       * ImageKit fileId.
       */
      imagekitFileId?: string | null;
      imagekitFilePath?: string | null;
      imagekitUrl?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      /**
       * ImageKit fileId.
       */
      imagekitFileId?: string | null;
      imagekitFilePath?: string | null;
      imagekitUrl?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      /**
       * ImageKit fileId.
       */
      imagekitFileId?: string | null;
      imagekitFilePath?: string | null;
      imagekitUrl?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      /**
       * ImageKit fileId.
       */
      imagekitFileId?: string | null;
      imagekitFilePath?: string | null;
      imagekitUrl?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      /**
       * ImageKit fileId.
       */
      imagekitFileId?: string | null;
      imagekitFilePath?: string | null;
      imagekitUrl?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      /**
       * ImageKit fileId.
       */
      imagekitFileId?: string | null;
      imagekitFilePath?: string | null;
      imagekitUrl?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Controls which SVG bottle is shown in the UI
   */
  oilVariant?: ('sesame' | 'coconut' | 'groundnut' | 'mustard' | 'sunflower' | 'blackSes' | 'castor') | null;
  /**
   * e.g. "Erode · Tamil Nadu"
   */
  region?: string | null;
  /**
   * Optional badge shown on card (e.g. "Best seller", "Limited")
   */
  tag?: string | null;
  categoryType?: ('cooking' | 'wellness' | 'gift-sets') | null;
  /**
   * URL-friendly identifier (auto-fill from name)
   */
  slug: string;
  /**
   * Short sentence shown on cards
   */
  tagline?: string | null;
  /**
   * Optional — overrides PDP global default for this product.
   */
  ratingDisplay?: string | null;
  /**
   * Optional — overrides PDP global default for this product.
   */
  reviewsDisplay?: string | null;
  /**
   * Optional — overrides PDP global star count for this product.
   */
  ratingStars?: number | null;
  description?: string | null;
  richDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (number | null) | Category;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  variants?:
    | {
        size: '250ml' | '500ml' | '1L' | '5L';
        sku: string;
        /**
         * Price in INR (₹)
         */
        price: number;
        /**
         * Maximum retail price (for strike-through)
         */
        mrp?: number | null;
        /**
         * Subscribe & save price
         */
        subscribePrice?: number | null;
        stock?: number | null;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  batch?: {
    batchNumber?: string | null;
    pressDate?: string | null;
    bestBefore?: string | null;
    /**
     * e.g. < 40°C
     */
    pressTemperature?: string | null;
    /**
     * e.g. 32% (cold-press standard)
     */
    yield?: string | null;
    /**
     * e.g. Erode, Tamil Nadu
     */
    farmLocation?: string | null;
    labReportUrl?: string | null;
  };
  benefits?:
    | {
        title: string;
        description?: string | null;
        icon?: ('leaf' | 'drop' | 'shield' | 'star' | 'heart') | null;
        id?: string | null;
      }[]
    | null;
  usageNote?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  status?: ('draft' | 'published' | 'archived') | null;
  featured?: boolean | null;
  bestSeller?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer orders. Created programmatically via checkout API.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * e.g. PT-20240601-0001
   */
  orderId: string;
  razorpayOrderId?: string | null;
  razorpayPaymentId?: string | null;
  customer?: (number | null) | User;
  customerName: string;
  customerEmail: string;
  customerPhone?: string | null;
  shippingAddress: {
    name: string;
    line1: string;
    line2?: string | null;
    city: string;
    state: string;
    pincode: string;
    phone?: string | null;
  };
  items: {
    product: number | Product;
    productName: string;
    variantSize: string;
    sku?: string | null;
    quantity: number;
    unitPrice: number;
    lineTotal: number;
    isSubscription?: boolean | null;
    id?: string | null;
  }[];
  subtotal: number;
  shippingFee?: number | null;
  discount?: number | null;
  couponCode?: string | null;
  total: number;
  paymentMethod?: ('upi' | 'card' | 'netbanking' | 'paylater' | 'cod') | null;
  paymentStatus?: ('pending' | 'paid' | 'failed' | 'refunded') | null;
  status?: ('pending' | 'confirmed' | 'packed' | 'shipped' | 'delivered' | 'cancelled' | 'returned') | null;
  trackingNumber?: string | null;
  /**
   * e.g. Delhivery, Shiprocket
   */
  courierPartner?: string | null;
  estimatedDelivery?: string | null;
  deliveredAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  product: number | Product;
  customer?: (number | null) | User;
  customerName: string;
  /**
   * e.g. Mumbai, Maharashtra
   */
  customerLocation?: string | null;
  rating: number;
  title: string;
  body: string;
  verifiedPurchase?: boolean | null;
  status?: ('pending' | 'approved' | 'rejected') | null;
  images?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  customerName: string;
  /**
   * e.g. "Bangalore" or "Chennai, Tamil Nadu"
   */
  customerLocation?: string | null;
  rating: number;
  /**
   * Short compelling title for the review card
   */
  title: string;
  body: string;
  product?: (number | null) | Product;
  verifiedPurchase?: boolean | null;
  /**
   * Include in homepage testimonials carousel
   */
  featuredOnHome?: boolean | null;
  status?: ('pending' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        ptHeroSection?:
          | T
          | {
              eyebrow?: T;
              headlineLine1?: T;
              headlineLine2?: T;
              headlineItalicWord?: T;
              body?: T;
              primaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              reviewRating?: T;
              reviewCount?: T;
              backgroundStyle?: T;
              id?: T;
              blockName?: T;
            };
        ptTrustStrip?:
          | T
          | {
              items?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    sub?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ptFeaturedProducts?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              body?: T;
              ctaLabel?: T;
              ctaHref?: T;
              products?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        ptProcessBanner?:
          | T
          | {
              eyebrow?: T;
              headlineLine1?: T;
              headlineLine2?: T;
              body?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        ptBenefitCards?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineItalic?: T;
              cards?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ptTestimonialsSection?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              source?: T;
              manualItems?:
                | T
                | {
                    customerName?: T;
                    customerLocation?: T;
                    initials?: T;
                    rating?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              maxItems?: T;
              id?: T;
              blockName?: T;
            };
        ptNewsletterBand?:
          | T
          | {
              headline?: T;
              body?: T;
              legalText?: T;
              buttonLabel?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        ptFAQSection?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
        ptEmptyState?:
          | T
          | {
              icon?: T;
              headline?: T;
              body?: T;
              ctaLabel?: T;
              ctaHref?: T;
              note?: T;
              id?: T;
              blockName?: T;
            };
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  imagekitFolder?: T;
  caption?: T;
  imagekitFileId?: T;
  imagekitFilePath?: T;
  imagekitUrl?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              imagekitFileId?: T;
              imagekitFilePath?: T;
              imagekitUrl?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              imagekitFileId?: T;
              imagekitFilePath?: T;
              imagekitUrl?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              imagekitFileId?: T;
              imagekitFilePath?: T;
              imagekitUrl?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              imagekitFileId?: T;
              imagekitFilePath?: T;
              imagekitUrl?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              imagekitFileId?: T;
              imagekitFilePath?: T;
              imagekitUrl?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              imagekitFileId?: T;
              imagekitFilePath?: T;
              imagekitUrl?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              imagekitFileId?: T;
              imagekitFilePath?: T;
              imagekitUrl?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  oilVariant?: T;
  region?: T;
  tag?: T;
  categoryType?: T;
  slug?: T;
  tagline?: T;
  ratingDisplay?: T;
  reviewsDisplay?: T;
  ratingStars?: T;
  description?: T;
  richDescription?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        size?: T;
        sku?: T;
        price?: T;
        mrp?: T;
        subscribePrice?: T;
        stock?: T;
        isDefault?: T;
        id?: T;
      };
  batch?:
    | T
    | {
        batchNumber?: T;
        pressDate?: T;
        bestBefore?: T;
        pressTemperature?: T;
        yield?: T;
        farmLocation?: T;
        labReportUrl?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  usageNote?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  status?: T;
  featured?: T;
  bestSeller?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderId?: T;
  razorpayOrderId?: T;
  razorpayPaymentId?: T;
  customer?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  shippingAddress?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        pincode?: T;
        phone?: T;
      };
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        variantSize?: T;
        sku?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        isSubscription?: T;
        id?: T;
      };
  subtotal?: T;
  shippingFee?: T;
  discount?: T;
  couponCode?: T;
  total?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  status?: T;
  trackingNumber?: T;
  courierPartner?: T;
  estimatedDelivery?: T;
  deliveredAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  customer?: T;
  customerName?: T;
  customerLocation?: T;
  rating?: T;
  title?: T;
  body?: T;
  verifiedPurchase?: T;
  status?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  customerName?: T;
  customerLocation?: T;
  rating?: T;
  title?: T;
  body?: T;
  product?: T;
  verifiedPurchase?: T;
  featuredOnHome?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  announcementBar?: {
    enabled?: boolean | null;
    /**
     * Full bar text
     */
    text?: string | null;
    /**
     * This exact substring will be shown in mustard gold — must appear in the text above
     */
    highlight?: string | null;
    /**
     * If set, the bar becomes a clickable link
     */
    link?: string | null;
  };
  /**
   * Order determines display order. Maximum 7 items recommended.
   */
  navLinks?:
    | {
        label: string;
        /**
         * e.g. /shop or /shop?category=wellness
         */
        href: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Display name in the header wordmark
   */
  logoText?: string | null;
  logoTagline?: string | null;
  /**
   * If set, shows image instead of wordmark text
   */
  logoImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline?: string | null;
  locations?: string | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  shopColumnHeading?: string | null;
  shopLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  learnColumnHeading?: string | null;
  learnLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  helpColumnHeading?: string | null;
  helpLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  legalColumnHeading?: string | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  legalEntityName?: string | null;
  gstin?: string | null;
  footerNote?: string | null;
  /**
   * e.g. "v2.4 · batch 047"
   */
  versionBadge?: string | null;
  /**
   * Used in cart drawer progress bar
   */
  freeShippingThreshold?: number | null;
  social?: {
    instagram?: string | null;
    youtube?: string | null;
    facebook?: string | null;
    twitter?: string | null;
    /**
     * e.g. https://wa.me/918904738151
     */
    whatsapp?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  announcementBar?: {
    enabled?: boolean | null;
    /**
     * Main announcement text
     */
    text?: string | null;
    /**
     * Text to highlight in mustard colour (must match text above)
     */
    highlight?: string | null;
  };
  /**
   * Used by cart drawer progress and checkout copy.
   */
  freeShippingThreshold?: number | null;
  contact?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    youtube?: string | null;
    twitter?: string | null;
  };
  footerTagline?: string | null;
  shopLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  companyLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Each tab controls one homepage band. Uncheck “Show this section” to hide it on the storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings".
 */
export interface HomepageSetting {
  id: number;
  cinematicEnabled?: boolean | null;
  cinematic?: {
    badge?: string | null;
    headlineLine1?: string | null;
    headlineItalic?: string | null;
    lead?: string | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
    /**
     * Cinematic hero background image (optional). Falls back to gradient.
     */
    image?: (number | null) | Media;
  };
  heroEnabled?: boolean | null;
  hero?: {
    eyebrow?: string | null;
    headlineLine1?: string | null;
    headlineLine2?: string | null;
    /**
     * Must match a substring of line 2 exactly
     */
    headlineItalicWord?: string | null;
    body?: string | null;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
    };
    secondaryCTA?: {
      label?: string | null;
      href?: string | null;
    };
    reviewRating?: string | null;
    reviewCount?: string | null;
    bottleVariant?: ('sesame' | 'coconut' | 'groundnut' | 'mustard' | 'sunflower' | 'blackSes') | null;
    /**
     * Hero side image (optional). Renders alongside the SVG bottle if set.
     */
    image?: (number | null) | Media;
    batchCaptionLeft?: string | null;
    batchCaptionRight?: string | null;
    pressWeekKicker?: string | null;
    pressWeekTitle?: string | null;
    backgroundStyle?: ('cream' | 'dark-green' | 'warm-white') | null;
  };
  pressMarqueeEnabled?: boolean | null;
  pressMarquee?: {
    items?:
      | {
          live?: boolean | null;
          italic?: boolean | null;
          text: string;
          stamp: string;
          id?: string | null;
        }[]
      | null;
  };
  trustStripEnabled?: boolean | null;
  trustStrip?:
    | {
        icon: 'leaf' | 'drop' | 'truck' | 'shield' | 'star' | 'check' | 'refresh';
        label: string;
        sub?: string | null;
        id?: string | null;
      }[]
    | null;
  featuredSectionEnabled?: boolean | null;
  featuredSection?: {
    eyebrow?: string | null;
    headline?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    columns?: ('2' | '3' | '4') | null;
    /**
     * Optional — leave empty to show the first active catalog products.
     */
    products?: (number | Product)[] | null;
  };
  traditionEnabled?: boolean | null;
  tradition: {
    eyebrow?: string | null;
    headlineLine1?: string | null;
    headlineItalic?: string | null;
    paragraph1: string;
    paragraph2: string;
    ctaPrimary?: {
      label?: string | null;
      href?: string | null;
    };
    ctaSecondary?: {
      label?: string | null;
      href?: string | null;
    };
    mediaCaptionLeft?: string | null;
    mediaCaptionRight?: string | null;
    /**
     * Tradition section photo (e.g. wood-press in village).
     */
    image?: (number | null) | Media;
  };
  processStepsEnabled?: boolean | null;
  processSteps: {
    eyebrow?: string | null;
    headlineLine1?: string | null;
    headlineItalic?: string | null;
    body: string;
    steps?:
      | {
          n: string;
          title: string;
          description: string;
          /**
           * Optional photo for this step.
           */
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
    /**
     * Optional banner photo above the steps.
     */
    bannerImage?: (number | null) | Media;
  };
  processSectionEnabled?: boolean | null;
  processSection?: {
    eyebrow?: string | null;
    headlineLine1?: string | null;
    headlineLine2?: string | null;
    body?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    /**
     * Optional background photo behind the stats band.
     */
    backgroundImage?: (number | null) | Media;
  };
  poeticEnabled?: boolean | null;
  poetic: {
    eyebrow?: string | null;
    headline1?: string | null;
    headline2?: string | null;
    body: string;
    /**
     * Optional muted background photo behind the poetic interlude.
     */
    backgroundImage?: (number | null) | Media;
  };
  whyColdPressedEnabled?: boolean | null;
  whyColdPressed?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineItalic?: string | null;
    scienceHref?: string | null;
    scienceLabel?: string | null;
    cards?:
      | {
          icon: 'leaf' | 'drop' | 'shield' | 'star' | 'check';
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  statsBandEnabled?: boolean | null;
  statsBand?: {
    eyebrow?: string | null;
    headlinePrefix?: string | null;
    headlineItalic?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          sub: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional muted background photo behind the stats band.
     */
    backgroundImage?: (number | null) | Media;
  };
  bestSellersEnabled?: boolean | null;
  bestSellers?: {
    eyebrow?: string | null;
    headline?: string | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
    source?: ('auto' | 'manual') | null;
    products?: (number | Product)[] | null;
  };
  bottleRowEnabled?: boolean | null;
  bottleRow?: {
    eyebrow?: string | null;
    headlineBefore?: string | null;
    headlineItalic?: string | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  testimonialsBandEnabled?: boolean | null;
  testimonialsBand?: {
    eyebrow?: string | null;
    headline?: string | null;
    source?: ('featured' | 'manual') | null;
    maxItems?: number | null;
    manualItems?:
      | {
          customerName: string;
          customerLocation?: string | null;
          initials?: string | null;
          rating?: number | null;
          title?: string | null;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  journalEnabled?: boolean | null;
  journal?: {
    eyebrow?: string | null;
    headlineLine1?: string | null;
    headlineLine2?: string | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
    posts?:
      | {
          tag: string;
          title: string;
          read?: string | null;
          slug: string;
          toneA?: string | null;
          toneB?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  newsletterEnabled?: boolean | null;
  newsletter?: {
    eyebrow?: string | null;
    headlineLine1?: string | null;
    headlineLine2Italic?: string | null;
    body?: string | null;
    legalText?: string | null;
    buttonLabel?: string | null;
  };
  faqEnabled?: boolean | null;
  faq?: {
    eyebrow?: string | null;
    headlinePrefix?: string | null;
    headlineItalic?: string | null;
    style?: ('light' | 'dark') | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional muted background photo behind the FAQ.
     */
    backgroundImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-listing".
 */
export interface ShopListing {
  id: number;
  /**
   * Use the tabs below to jump between SEO, headlines, filters, and media.
   */
  plp?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    eyebrow?: string | null;
    headline?: string | null;
    /**
     * Use {count} and {oilWord} — oilWord becomes "oil" or "oils" automatically.
     */
    introWithCount?: string | null;
    /**
     * Shown when ?cat= (category slug) is set. Use {category} for the category title.
     */
    eyebrowWhenCategory?: string | null;
    /**
     * Headline when a category filter is active. Placeholders: {category}.
     */
    headlineWhenCategory?: string | null;
    /**
     * Intro when ?cat= is set. Placeholders: {count}, {oilWord}, {category} (category title).
     */
    introWhenCategory?: string | null;
    filterCategoryLabel?: string | null;
    filterSortLabel?: string | null;
    categoryFilters?:
      | {
          label: string;
          /**
           * Query param value; empty string = All
           */
          value?: string | null;
          id?: string | null;
        }[]
      | null;
    sortOptions?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    emptyTitle?: string | null;
    emptyCtaLabel?: string | null;
    emptyCtaHref?: string | null;
    /**
     * Optional — reserved for future PLP banner
     */
    decorativeImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-detail".
 */
export interface ProductDetail {
  id: number;
  /**
   * Defaults for PDP UI; products can override ratings where configured.
   */
  pdp?: {
    ratingDisplay?: string | null;
    reviewsDisplay?: string | null;
    /**
     * Filled stars shown when the product has no per-product override.
     */
    starsCount?: number | null;
    /**
     * Maps each variant size value to the label shown in the shop.
     */
    variantSizeLabels?:
      | {
          sizeValue: '250ml' | '500ml' | '1L' | '5L';
          label: string;
          id?: string | null;
        }[]
      | null;
    batchBadge?: string | null;
    labelPressDate?: string | null;
    labelTemperature?: string | null;
    labelYield?: string | null;
    labelOrigin?: string | null;
    shippingBullets?:
      | {
          icon?: ('leaf' | 'drop' | 'truck' | 'shield' | 'package' | 'star') | null;
          text: string;
          id?: string | null;
        }[]
      | null;
    aboutHeading?: string | null;
    howToUseHeading?: string | null;
    benefitsHeading?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart".
 */
export interface Cart {
  id: number;
  /**
   * Slide-out basket (Zustand-driven UI).
   */
  cartDrawer?: {
    title?: string | null;
    emptyTitle?: string | null;
    emptySubtitle?: string | null;
    browseButtonLabel?: string | null;
    /**
     * {remaining} is replaced with formatted rupees
     */
    freeShippingProgress?: string | null;
    freeShippingUnlocked?: string | null;
    /**
     * Uses free-shipping threshold from Site Settings
     */
    flatShippingAmount?: number | null;
    subtotalLabel?: string | null;
    shippingLabel?: string | null;
    shippingFreeLabel?: string | null;
    totalLabel?: string | null;
    continueCheckoutLabel?: string | null;
    continueShoppingLabel?: string | null;
    removeLineLabel?: string | null;
    subscribeSuffix?: string | null;
    /**
     * Badge on cart lines when the item is a subscription.
     */
    subscribePillLabel?: string | null;
  };
  /**
   * Full cart route copy and layout hints.
   */
  cartPage?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    listingEyebrow?: string | null;
    breadcrumbHomeLabel?: string | null;
    breadcrumbHomeHref?: string | null;
    breadcrumbCurrentLabel?: string | null;
    /**
     * Fallback single headline if the split headline fields below are empty.
     */
    headline?: string | null;
    /**
     * Shown before the mustard italic phrase (e.g. “Three bottles, ”).
     */
    headlineLineBeforeItalic?: string | null;
    /**
     * Mustard italic display line (e.g. “well chosen.”).
     */
    headlineItalic?: string | null;
    /**
     * Optional text after the italic phrase.
     */
    headlineLineAfterItalic?: string | null;
    subhead?: string | null;
    heroImage?: (number | null) | Media;
    checkoutHref?: string | null;
    continueShoppingHref?: string | null;
    orderSummaryEyebrow?: string | null;
    /**
     * {count} = item count · {bottleWord} = singular/plural below. If empty, falls back to the drawer “Subtotal” label.
     */
    subtotalLineTemplate?: string | null;
    bottleWordSingular?: string | null;
    bottleWordPlural?: string | null;
    gstLabel?: string | null;
    gstDisplayValue?: string | null;
    promoCodePlaceholder?: string | null;
    promoApplyLabel?: string | null;
    securedPaymentLine?: string | null;
    trustFootnote?: string | null;
    /**
     * Leave empty to hide “Save for later” (link-only for now).
     */
    saveForLaterLabel?: string | null;
    saveForLaterHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account".
 */
export interface Account {
  id: number;
  /**
   * Account dashboard chrome.
   */
  account?: {
    metaTitle?: string | null;
    pageTitle?: string | null;
    profileCardTitle?: string | null;
    labelName?: string | null;
    labelEmail?: string | null;
    ordersCardTitle?: string | null;
    viewAllOrdersLabel?: string | null;
    emptyOrdersMessage?: string | null;
    shopNowLabel?: string | null;
    navItems?:
      | {
          href: string;
          label: string;
          icon?: ('user' | 'package' | 'heart' | 'refresh') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-success".
 */
export interface OrderSuccess {
  id: number;
  /**
   * Thank-you page and timeline copy.
   */
  orderSuccess?: {
    metaTitle?: string | null;
    /**
     * Optional logo for the top bar; if empty the site falls back to /logo-wordmark.svg.
     */
    headerWordmark?: (number | null) | Media;
    headerAsideLabel?: string | null;
    /**
     * Shown when ?id= is present. Use {id} for the order reference.
     */
    orderRefEyebrowTemplate?: string | null;
    thankYouHeadline?: string | null;
    /**
     * When ?name= is set, headline becomes prefix + italic name + suffix.
     */
    thankYouLinePrefix?: string | null;
    thankYouNameSuffix?: string | null;
    thankYouBody?: string | null;
    /**
     * Secondary line with raw id
     */
    orderRefPrefix?: string | null;
    /**
     * Shown under primary actions.
     */
    confirmationNote?: string | null;
    trackOrderLabel?: string | null;
    trackOrderHref?: string | null;
    downloadInvoiceLabel?: string | null;
    downloadInvoiceHref?: string | null;
    nextStepsTitle?: string | null;
    timelineSteps?:
      | {
          label: string;
          sub: string;
          /**
           * Small mono line under the title (dates, windows, etc.)
           */
          stamp?: string | null;
          done?: boolean | null;
          /**
           * Current step highlight
           */
          active?: boolean | null;
          id?: string | null;
        }[]
      | null;
    upsellTitle?: string | null;
    upsellBody?: string | null;
    upsellCtaLabel?: string | null;
    upsellCtaHref?: string | null;
    continueShoppingLabel?: string | null;
    viewOrdersLabel?: string | null;
    /**
     * Caption under hero image — left side
     */
    heroImageCaptionLeft?: string | null;
    /**
     * Caption under hero image — right side
     */
    heroImageCaptionRight?: string | null;
    celebrationImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  announcementBar?:
    | T
    | {
        enabled?: T;
        text?: T;
        highlight?: T;
        link?: T;
      };
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  logoText?: T;
  logoTagline?: T;
  logoImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  locations?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  shopColumnHeading?: T;
  shopLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  learnColumnHeading?: T;
  learnLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  helpColumnHeading?: T;
  helpLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  legalColumnHeading?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  legalEntityName?: T;
  gstin?: T;
  footerNote?: T;
  versionBadge?: T;
  freeShippingThreshold?: T;
  social?:
    | T
    | {
        instagram?: T;
        youtube?: T;
        facebook?: T;
        twitter?: T;
        whatsapp?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  announcementBar?:
    | T
    | {
        enabled?: T;
        text?: T;
        highlight?: T;
      };
  freeShippingThreshold?: T;
  contact?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        youtube?: T;
        twitter?: T;
      };
  footerTagline?: T;
  shopLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  companyLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings_select".
 */
export interface HomepageSettingsSelect<T extends boolean = true> {
  cinematicEnabled?: T;
  cinematic?:
    | T
    | {
        badge?: T;
        headlineLine1?: T;
        headlineItalic?: T;
        lead?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        image?: T;
      };
  heroEnabled?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        headlineLine1?: T;
        headlineLine2?: T;
        headlineItalicWord?: T;
        body?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
            };
        reviewRating?: T;
        reviewCount?: T;
        bottleVariant?: T;
        image?: T;
        batchCaptionLeft?: T;
        batchCaptionRight?: T;
        pressWeekKicker?: T;
        pressWeekTitle?: T;
        backgroundStyle?: T;
      };
  pressMarqueeEnabled?: T;
  pressMarquee?:
    | T
    | {
        items?:
          | T
          | {
              live?: T;
              italic?: T;
              text?: T;
              stamp?: T;
              id?: T;
            };
      };
  trustStripEnabled?: T;
  trustStrip?:
    | T
    | {
        icon?: T;
        label?: T;
        sub?: T;
        id?: T;
      };
  featuredSectionEnabled?: T;
  featuredSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        body?: T;
        ctaLabel?: T;
        ctaHref?: T;
        columns?: T;
        products?: T;
      };
  traditionEnabled?: T;
  tradition?:
    | T
    | {
        eyebrow?: T;
        headlineLine1?: T;
        headlineItalic?: T;
        paragraph1?: T;
        paragraph2?: T;
        ctaPrimary?:
          | T
          | {
              label?: T;
              href?: T;
            };
        ctaSecondary?:
          | T
          | {
              label?: T;
              href?: T;
            };
        mediaCaptionLeft?: T;
        mediaCaptionRight?: T;
        image?: T;
      };
  processStepsEnabled?: T;
  processSteps?:
    | T
    | {
        eyebrow?: T;
        headlineLine1?: T;
        headlineItalic?: T;
        body?: T;
        steps?:
          | T
          | {
              n?: T;
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        bannerImage?: T;
      };
  processSectionEnabled?: T;
  processSection?:
    | T
    | {
        eyebrow?: T;
        headlineLine1?: T;
        headlineLine2?: T;
        body?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
        backgroundImage?: T;
      };
  poeticEnabled?: T;
  poetic?:
    | T
    | {
        eyebrow?: T;
        headline1?: T;
        headline2?: T;
        body?: T;
        backgroundImage?: T;
      };
  whyColdPressedEnabled?: T;
  whyColdPressed?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineItalic?: T;
        scienceHref?: T;
        scienceLabel?: T;
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  statsBandEnabled?: T;
  statsBand?:
    | T
    | {
        eyebrow?: T;
        headlinePrefix?: T;
        headlineItalic?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              sub?: T;
              id?: T;
            };
        backgroundImage?: T;
      };
  bestSellersEnabled?: T;
  bestSellers?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        source?: T;
        products?: T;
      };
  bottleRowEnabled?: T;
  bottleRow?:
    | T
    | {
        eyebrow?: T;
        headlineBefore?: T;
        headlineItalic?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  testimonialsBandEnabled?: T;
  testimonialsBand?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        source?: T;
        maxItems?: T;
        manualItems?:
          | T
          | {
              customerName?: T;
              customerLocation?: T;
              initials?: T;
              rating?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  journalEnabled?: T;
  journal?:
    | T
    | {
        eyebrow?: T;
        headlineLine1?: T;
        headlineLine2?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        posts?:
          | T
          | {
              tag?: T;
              title?: T;
              read?: T;
              slug?: T;
              toneA?: T;
              toneB?: T;
              id?: T;
            };
      };
  newsletterEnabled?: T;
  newsletter?:
    | T
    | {
        eyebrow?: T;
        headlineLine1?: T;
        headlineLine2Italic?: T;
        body?: T;
        legalText?: T;
        buttonLabel?: T;
      };
  faqEnabled?: T;
  faq?:
    | T
    | {
        eyebrow?: T;
        headlinePrefix?: T;
        headlineItalic?: T;
        style?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        backgroundImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-listing_select".
 */
export interface ShopListingSelect<T extends boolean = true> {
  plp?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        eyebrow?: T;
        headline?: T;
        introWithCount?: T;
        eyebrowWhenCategory?: T;
        headlineWhenCategory?: T;
        introWhenCategory?: T;
        filterCategoryLabel?: T;
        filterSortLabel?: T;
        categoryFilters?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        sortOptions?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        emptyTitle?: T;
        emptyCtaLabel?: T;
        emptyCtaHref?: T;
        decorativeImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-detail_select".
 */
export interface ProductDetailSelect<T extends boolean = true> {
  pdp?:
    | T
    | {
        ratingDisplay?: T;
        reviewsDisplay?: T;
        starsCount?: T;
        variantSizeLabels?:
          | T
          | {
              sizeValue?: T;
              label?: T;
              id?: T;
            };
        batchBadge?: T;
        labelPressDate?: T;
        labelTemperature?: T;
        labelYield?: T;
        labelOrigin?: T;
        shippingBullets?:
          | T
          | {
              icon?: T;
              text?: T;
              id?: T;
            };
        aboutHeading?: T;
        howToUseHeading?: T;
        benefitsHeading?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart_select".
 */
export interface CartSelect<T extends boolean = true> {
  cartDrawer?:
    | T
    | {
        title?: T;
        emptyTitle?: T;
        emptySubtitle?: T;
        browseButtonLabel?: T;
        freeShippingProgress?: T;
        freeShippingUnlocked?: T;
        flatShippingAmount?: T;
        subtotalLabel?: T;
        shippingLabel?: T;
        shippingFreeLabel?: T;
        totalLabel?: T;
        continueCheckoutLabel?: T;
        continueShoppingLabel?: T;
        removeLineLabel?: T;
        subscribeSuffix?: T;
        subscribePillLabel?: T;
      };
  cartPage?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        listingEyebrow?: T;
        breadcrumbHomeLabel?: T;
        breadcrumbHomeHref?: T;
        breadcrumbCurrentLabel?: T;
        headline?: T;
        headlineLineBeforeItalic?: T;
        headlineItalic?: T;
        headlineLineAfterItalic?: T;
        subhead?: T;
        heroImage?: T;
        checkoutHref?: T;
        continueShoppingHref?: T;
        orderSummaryEyebrow?: T;
        subtotalLineTemplate?: T;
        bottleWordSingular?: T;
        bottleWordPlural?: T;
        gstLabel?: T;
        gstDisplayValue?: T;
        promoCodePlaceholder?: T;
        promoApplyLabel?: T;
        securedPaymentLine?: T;
        trustFootnote?: T;
        saveForLaterLabel?: T;
        saveForLaterHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account_select".
 */
export interface AccountSelect<T extends boolean = true> {
  account?:
    | T
    | {
        metaTitle?: T;
        pageTitle?: T;
        profileCardTitle?: T;
        labelName?: T;
        labelEmail?: T;
        ordersCardTitle?: T;
        viewAllOrdersLabel?: T;
        emptyOrdersMessage?: T;
        shopNowLabel?: T;
        navItems?:
          | T
          | {
              href?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-success_select".
 */
export interface OrderSuccessSelect<T extends boolean = true> {
  orderSuccess?:
    | T
    | {
        metaTitle?: T;
        headerWordmark?: T;
        headerAsideLabel?: T;
        orderRefEyebrowTemplate?: T;
        thankYouHeadline?: T;
        thankYouLinePrefix?: T;
        thankYouNameSuffix?: T;
        thankYouBody?: T;
        orderRefPrefix?: T;
        confirmationNote?: T;
        trackOrderLabel?: T;
        trackOrderHref?: T;
        downloadInvoiceLabel?: T;
        downloadInvoiceHref?: T;
        nextStepsTitle?: T;
        timelineSteps?:
          | T
          | {
              label?: T;
              sub?: T;
              stamp?: T;
              done?: T;
              active?: T;
              id?: T;
            };
        upsellTitle?: T;
        upsellBody?: T;
        upsellCtaLabel?: T;
        upsellCtaHref?: T;
        continueShoppingLabel?: T;
        viewOrdersLabel?: T;
        heroImageCaptionLeft?: T;
        heroImageCaptionRight?: T;
        celebrationImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}